#ifndef ASTAR_H
#define ASTAR_H

#pragma once

/* Generated by cbindgen. DO NOT EDIT. Regenerate with scripts/check-cbindgen.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success.
 */
#define IAX_OK 0

/**
 * A Rust panic was caught at the boundary (should never happen; a bug).
 */
#define IAX_ERR_PANIC -1

/**
 * A required handle or out-pointer argument was NULL.
 */
#define IAX_ERR_NULL -2

/**
 * Operation needs an active call but none exists.
 */
#define IAX_ERR_NOT_CONNECTED -3

/**
 * `connect`/`connect_wt` while a call is already live.
 */
#define IAX_ERR_ALREADY_CONNECTED -4

/**
 * Portal/token-mint problem (no portal config, login failure, etc.).
 */
#define IAX_ERR_PORTAL -5

/**
 * Node resolution (DNS) failed.
 */
#define IAX_ERR_RESOLVE -6

/**
 * Audio enumeration / device error.
 */
#define IAX_ERR_AUDIO -7

/**
 * Underlying IAX client error.
 */
#define IAX_ERR_IAX -8

/**
 * Serial-PTT wiring error.
 */
#define IAX_ERR_SERIAL -9

/**
 * A `const char*` argument was not valid UTF-8.
 */
#define IAX_ERR_UTF8 -10

/**
 * Operation not supported in the current mode (e.g. switching to an
 * unimplemented mode).
 */
#define IAX_ERR_UNSUPPORTED -11

/**
 * Operation not valid in the current operating mode (e.g. `connect` while in
 * Node mode).
 */
#define IAX_ERR_MODE_MISMATCH -12

/**
 * Inbound listener failed to bind (port in use, permission denied, etc.).
 */
#define IAX_ERR_LISTEN -13

/**
 * Node is at its maximum inbound call capacity; the offer was rejected.
 */
#define IAX_ERR_AT_CAPACITY -14

/**
 * `iax_station_send_dtmf` was given a character that is not a valid DTMF
 * key (`0-9`, `*`, `#`, `A-D`).
 */
#define IAX_ERR_INVALID_DIGIT -15

/**
 * A link-layer operation failed (no such link, dial failure, bad address).
 */
#define IAX_ERR_LINK -16

/**
 * `iax_station_send_dtmf_string` while a previous sequence is still playing
 * (iax-4b7a). Cancel it or wait for it to finish.
 */
#define IAX_ERR_DTMF_BUSY -17

/**
 * M17 error (iax-f2b8 Task 4/5) — an invalid module/callsign, a link/device
 * failure, or the `m17` feature isn't compiled in. Returned by
 * [`iax_station_connect_m17`].
 */
#define IAX_ERR_M17 -18

/**
 * D-Star error (iax-a9d4 Task 6 built RX; iax-2f6b added TX; iax-4c8e
 * exposed both here) — an invalid module/callsign, a link failure, no
 * `ThumbDV` attached, or the `dstar` feature isn't compiled in. D-Star is
 * full-transceive: a live session keys/unkeys like any other call, so this
 * is not returned for a PTT/key attempt. Returned by
 * [`iax_station_connect_dstar`].
 */
#define IAX_ERR_DSTAR -19

/**
 * YSF error (iax-e8a4): a link that could not be made, or the `ysf` feature
 * not being compiled in. Read `iax_station_last_error` for which.
 */
#define IAX_ERR_YSF -20

/**
 * NXDN error (iax-b9c2): a link that could not be made, a callsign/radio
 * id/talkgroup the wire cannot carry, a refused key (NXDN is receive-only —
 * see `astar_console::nxdn`'s Transmit section), or the `nxdn` feature not
 * being compiled in. Read `iax_station_last_error` for which.
 */
#define IAX_ERR_NXDN -21

/**
 * DMR error (iax-d4f7): an unknown network slug, a network the operator has
 * not opted in to, a radio id/callsign/talkgroup/timeslot the wire cannot
 * carry, an empty master password, a login the master refused, a refused key
 * (DMR is receive-only — see `astar_console::dmr`'s Transmit section), or the
 * `dmr` feature not being compiled in. Read `iax_station_last_error` for
 * which — it never carries the password.
 */
#define IAX_ERR_DMR -22

/**
 * Number of log-spaced dBFS bins [`iax_station_mic_spectrum`] writes when
 * monitoring (iax-e73e). Size the `out` array to (at least) this; a larger
 * buffer is fine (the extra entries are left untouched). A literal here so
 * cbindgen can emit it as a `#define`; a `const` assert below keeps it pinned
 * to the engine's [`astar_station::SPECTRUM_BINS`].
 */
#define IAX_SPECTRUM_BINS 256

/**
 * Top-level operating mode. Mirrors `astar_station::OperatingMode`.
 */
typedef enum {
  /**
   * Dial-out Web-Transceiver client (default).
   */
  IaxMode_Wt = 0,
  /**
   * Inbound IAX2 node (accept calls, bridge to the local handset).
   */
  IaxMode_Node = 1,
} IaxMode;

/**
 * How a node answers inbound calls. Mirrors `astar_station::AnswerPolicy`.
 */
typedef enum {
  /**
   * Auto-accept the inbound offer and bridge it to the local handset.
   */
  IaxAnswerPolicy_Auto = 0,
  /**
   * Surface the offer as an [`IaxEventKind::Incoming`] event; the operator
   * then calls [`iax_station_answer`] / [`iax_station_reject`].
   */
  IaxAnswerPolicy_Manual = 1,
} IaxAnswerPolicy;

/**
 * Inbound-authentication policy for a node listener. Mirrors
 * `astar_iax::IncomingAuthPolicy`. Note: per-user credentials for `Required`
 * are not yet configurable across this ABI (a future revision); `Required`
 * with no credentials rejects everyone, so use `Off` for an open dev dial-in.
 */
typedef enum {
  /**
   * Every inbound NEW must authenticate (unknown user → REJECT).
   */
  IaxAuthPolicy_Required = 0,
  /**
   * Challenge only if the peer's username maps to a held credential.
   */
  IaxAuthPolicy_Optional = 1,
  /**
   * Never challenge (accept anonymous). Permissive — dev dial-in only.
   */
  IaxAuthPolicy_Off = 2,
} IaxAuthPolicy;

/**
 * How [`iax_station_send_dtmf`] emits digits on the active call. Mirrors
 * `astar_station::DtmfMode` (iax-7fff).
 */
typedef enum {
  /**
   * Synthesize the dual-tone waveform into the call's TX audio path
   * (in-band; default) — for nodes/paths that only decode audio tones.
   */
  IaxDtmfMode_InBand = 0,
  /**
   * Send out-of-band IAX2 protocol DTMF frames (`DTMF BEGIN`/`DTMF END`) —
   * what Asterisk/`AllStar` expects by default. The tone duration does not
   * apply; the frame pair carries the digit only.
   */
  IaxDtmfMode_Protocol = 1,
} IaxDtmfMode;

/**
 * Call lifecycle status. Mirrors `astar_station::CallStatus`, collapsing
 * `Hangup`/`Failed` into a single [`IaxStatus::Hangup`] (the human-readable
 * reason is available via [`iax_station_next_event`], not this enum).
 */
typedef enum {
  /**
   * No call in progress.
   */
  IaxStatus_Idle = 0,
  /**
   * NEW sent, awaiting answer.
   */
  IaxStatus_Dialing = 1,
  /**
   * Peer answered; media flowing.
   */
  IaxStatus_Answered = 2,
  /**
   * Call ended (normal hangup or failed dial).
   */
  IaxStatus_Hangup = 3,
} IaxStatus;

/**
 * Which mic noise-reduction chain is live. Mirrors
 * `astar_audio::DenoiseChain` (`docs/design/noise-suppression.md`).
 *
 * Read-only. It exists because the 48 kHz guard is otherwise invisible: a
 * capture device that cannot offer 48 kHz silently gets the classical
 * chain, and that is indistinguishable from a bug without being told.
 * Discriminants are stable and mirrored on the Rust and Swift sides; add
 * variants at the end.
 */
typedef enum {
  /**
   * No mic lane is open, so no chain is running.
   */
  IaxDenoiseChain_NotCapturing = 0,
  /**
   * Capturing, but noise reduction is switched off.
   */
  IaxDenoiseChain_Off = 1,
  /**
   * Neural (RNNoise) at device rate, hum filter after it, no gate.
   */
  IaxDenoiseChain_Neural = 2,
  /**
   * The classical hum filter + noise gate. Either the device could not
   * give 48 kHz, or `ASTAR_MIC_DENOISE=legacy` asked for it.
   */
  IaxDenoiseChain_FilterGate = 3,
} IaxDenoiseChain;

/**
 * The kind of a drained lifecycle event (see [`iax_station_next_event`]).
 */
typedef enum {
  /**
   * No event was queued.
   */
  IaxEventKind_None = 0,
  /**
   * The peer answered; media is flowing.
   */
  IaxEventKind_Answered = 1,
  /**
   * The remote end keyed/unkeyed (see [`IaxEvent::remote_ptt`]).
   */
  IaxEventKind_RemotePtt = 2,
  /**
   * The call ended (normal hangup or failed dial).
   */
  IaxEventKind_Hangup = 3,
  /**
   * The operating mode changed (Wt <-> Node). The new mode is not carried
   * across this ABI yet; read it from a status query.
   */
  IaxEventKind_ModeChanged = 4,
  /**
   * An inbound call is ringing (Node/Manual); read the caller id from a
   * status query.
   */
  IaxEventKind_Incoming = 5,
  /**
   * Outbound node registration succeeded (Phase 7). Secret-free.
   */
  IaxEventKind_Registered = 6,
  /**
   * Outbound node registration failed (Phase 7). The reason string is not
   * carried across the ABI here; it is secret-free.
   */
  IaxEventKind_RegisterFailed = 7,
} IaxEventKind;

/**
 * Link mode over the C ABI. Mirrors `astar_iax::LinkMode`.
 */
typedef enum {
  /**
   * Mic routed + RX mixed: transmit to and hear the peer.
   */
  IaxLinkMode_Transceive = 0,
  /**
   * Hear the peer (and relay onward in conference mode); never transmit.
   */
  IaxLinkMode_Monitor = 1,
  /**
   * Hear the peer on the local speaker only; never relayed, never sent to.
   */
  IaxLinkMode_LocalMonitor = 2,
} IaxLinkMode;

/**
 * What a drained link event was. `None` means "no event pending".
 */
typedef enum {
  /**
   * No event was pending.
   */
  IaxLinkEventKind_None = 0,
  /**
   * The link's call reached Active.
   */
  IaxLinkEventKind_Connected = 1,
  /**
   * The link's call ended / dropped.
   */
  IaxLinkEventKind_Disconnected = 2,
  /**
   * The link's local PTT changed (see `keyed`).
   */
  IaxLinkEventKind_Keyed = 3,
} IaxLinkEventKind;

/**
 * Opaque station handle. Heap-allocated by [`iax_station_new`], freed by
 * [`iax_station_free`]. The only cross-boundary heap object; treat it as a
 * pointer you must not dereference, copy-and-free twice, or use after free.
 */
typedef struct IaxStation IaxStation;

/**
 * Station configuration passed to [`iax_station_new`]. All fields are
 * **borrowed** `const char*` (the library copies what it needs; the caller
 * keeps ownership and may free them right after the call returns).
 *
 * A NULL pointer means "unset": NULL `input`/`output` selects the system
 * default device; NULL `secret` defaults to the guest secret `"allstar"`; the
 * three `portal_*` fields enable the WT path only when **all three** are
 * non-NULL.
 *
 * Note: there is intentionally no `secret`-in-snapshot field anywhere; the
 * `secret` here is an in-param consumed into the station, never echoed back.
 */
typedef struct {
  /**
   * Capture device name substring, or NULL for the system default.
   */
  const char *input;
  /**
   * Playback device name substring, or NULL for the system default.
   */
  const char *output;
  /**
   * `AllStar` portal user (WT path), or NULL.
   */
  const char *portal_user;
  /**
   * `AllStar` portal password (WT path), or NULL. Consumed into the station's
   * `PortalCredentials`; never stored in any out-struct or logged.
   */
  const char *portal_pass;
  /**
   * `AllStar` node selector for token minting (WT path), or NULL. Optional:
   * the portal mints without one, so NULL (or empty) means "no node" and
   * the WT path is enabled by `portal_user` + `portal_pass` alone.
   */
  const char *portal_node;
  /**
   * Guest secret, or NULL for the default `"allstar"`.
   */
  const char *secret;
  /**
   * Codec negotiation policy for OUTBOUND calls placed by this station
   * (iax-4348/iax-3e53), as a config string: `"ulaw_only"` (the library
   * default), `"allow_slin"`, `"prefer_slin"`, or `"prefer_slin16"`
   * (16 kHz wideband). NULL, empty, or `"default"` selects the library
   * default. Any other string fails construction ([`iax_station_new`]
   * returns NULL) rather than silently defaulting.
   *
   * Construction-time only — the station's audio pipeline rate is pinned
   * by this policy when the engine is built, so there is deliberately no
   * runtime setter; changing the policy means rebuilding the station.
   */
  const char *codec_policy;
} IaxConfig;

/**
 * Node-mode configuration passed to [`iax_station_set_node_config`].
 *
 * **Secret-free by construction**: there is no password field anywhere here.
 * The registrar password (for `registrar`/`register_user`) is supplied only at
 * runtime through the callback registered via
 * [`iax_station_set_credential_resolver`]. All `const char*` are borrowed for
 * the duration of the call.
 */
typedef struct {
  /**
   * Listener bind address `"host:port"`, or NULL for `"0.0.0.0:4569"`.
   */
  const char *bind;
  /**
   * Auto vs manual answer.
   */
  IaxAnswerPolicy answer;
  /**
   * Inbound auth policy.
   */
  IaxAuthPolicy auth;
  /**
   * Upstream registrar `"host:port"` to register AS a node, or NULL to only
   * listen (no registration). Resolve the node→host:port yourself.
   */
  const char *registrar;
  /**
   * The node id to register AS (e.g. `"77777"`), required when `registrar`
   * is non-NULL, otherwise ignored. May be NULL when not registering.
   */
  const char *register_user;
  /**
   * Requested registration refresh interval in seconds, or `0` for `60`.
   */
  uint32_t refresh_secs;
} IaxNodeConfig;

/**
 * Resolve a registrar/auth username to its secret. Registered via
 * [`iax_station_set_credential_resolver`] and invoked by the library when it
 * needs the password (e.g. to answer a registrar's MD5 challenge).
 *
 * Contract: write the NUL-terminated secret for `user` into `out` (a buffer of
 * `cap` bytes) and return [`IAX_OK`]; return any non-zero value to signal "no
 * secret" (the library treats the secret as empty). `user_data` is the opaque
 * pointer passed at registration time. The callback may be invoked from a
 * background thread, so whatever `user_data` points at must be thread-safe.
 */
typedef int (*IaxCredentialResolver)(const char *user, char *out, uintptr_t cap, void *user_data);

/**
 * A snapshot of live call state. Caller-allocated; filled by
 * [`iax_station_snapshot`].
 */
typedef struct {
  /**
   * Current lifecycle status.
   */
  IaxStatus status;
  /**
   * Local transmit (PTT) state.
   */
  bool ptt;
  /**
   * Remote-keyed state.
   */
  bool remote_ptt;
  /**
   * TX (transmitted, post-DSP) level in dBFS, `-60.0..=0.0`. Meters only
   * while keyed; floors to -60 when unkeyed.
   */
  float tx_db;
  /**
   * RX (decoded node audio) level in dBFS, `-60.0..=0.0`.
   */
  float rx_db;
  /**
   * Continuous mic INPUT level in dBFS, `-60.0..=0.0`, metered even while
   * unkeyed (post-gain, pre-noise-reduction). Drive VOX from this field, not
   * `tx_db` (iax-5c30). A plain dBFS float, carrying no sensitive data.
   */
  float input_db;
  /**
   * Smoothed round-trip estimate in milliseconds, or `-1` if unknown.
   */
  int rtt_ms;
  /**
   * Current top-level operating mode (WT dial-out vs inbound Node).
   */
  IaxMode mode;
  /**
   * Cumulative voice-ts-ladder re-anchors (>80 ms TX-clock drift events;
   * iax-5530/iax-9e55). A growing value signals choppy TX. A plain `u64`
   * health counter, credential-free.
   */
  uint64_t tx_reanchors;
  /**
   * Cumulative cpal capture overruns (dropped input buffers — holes in the
   * captured mic PCM; iax-9e55) on the active call's routed mic. The lead
   * suspect for choppy TX; `0` when monitor-only. A plain `u64` health
   * counter, credential-free.
   */
  uint64_t tx_capture_overruns;
  /**
   * Cumulative RX underruns on the active call's output bus (iax-rxjb):
   * device callbacks that got no audio at all while somebody was still
   * talking. The receive-side counterpart of `tx_capture_overruns` — the
   * number that grows while received audio stutters. `0` when idle. A plain
   * `u64` health counter, credential-free.
   */
  uint64_t rx_underruns;
  /**
   * Estimated network jitter on the active call's receive path, ms
   * (iax-rxjb). `0` when idle, or with the jitter buffer switched off.
   */
  unsigned int rx_jitter_ms;
  /**
   * Current RX jitter-buffer depth in ms (iax-rxjb): how much received
   * audio is being held back to ride out the network. `0` when the buffer
   * isn't running.
   */
  unsigned int rx_jb_depth_ms;
  /**
   * Frames the RX jitter buffer expected and never saw (iax-rxjb); each one
   * cost 20 ms of interpolated silence. `0` when idle.
   */
  uint64_t rx_frames_lost;
  /**
   * Frames that arrived after their play time and were thrown away
   * (iax-rxjb). `0` when idle.
   */
  uint64_t rx_frames_late;
  /**
   * Frames that arrived out of timestamp order (iax-rxjb). `0` when idle.
   */
  uint64_t rx_frames_ooo;
  /**
   * `true` while the RX jitter buffer is running (iax-rxjb). Reported so a
   * client renders what the engine is doing, not what it last asked for.
   */
  bool rx_jb_enabled;
  /**
   * Floor of the RX jitter buffer's adaptive depth in ms — the effective,
   * clamped value (iax-rxjb).
   */
  unsigned int rx_jb_min_ms;
  /**
   * Ceiling of the RX jitter buffer's adaptive depth in ms — the effective,
   * clamped value (iax-rxjb).
   */
  unsigned int rx_jb_max_ms;
  /**
   * Which mic noise-reduction chain is live (`IaxDenoiseChain`). A plain
   * enum, credential-free.
   */
  IaxDenoiseChain denoise_chain;
  /**
   * The rate the capture stream opened at, in Hz, or `0` when no mic lane
   * is open. Pair it with `denoise_chain`: at 48000 the neural stage can
   * run, below that it cannot and the classical chain is used instead. A
   * plain sample rate, credential-free.
   */
  unsigned int denoise_device_rate;
  /**
   * `true` when `denoise_chain` was MEASURED from a running capture
   * stream; `false` when it is a prediction of what the next one will do,
   * from the current settings and the selected device's advertised rates.
   *
   * The idle prediction is why a UI can show this before anything is
   * capturing, which is when it gets configured — but a prediction must
   * not be presented as an observation, so render it differently.
   */
  bool denoise_live;
  /**
   * Negotiated voice codec of the active call as its IAX2 format bit
   * (iax-3e53): `0` = none (idle or still negotiating), `4` = G.711 µ-law,
   * `8` = G.711 A-law, `64` = slin (8 kHz linear), `32768` = slin16
   * (16 kHz wideband). A plain codec id, credential-free.
   */
  unsigned int negotiated_format;
  /**
   * Digits already sent of the active [`iax_station_send_dtmf_string`]
   * sequence (iax-4b7a); `0` when no sequence is playing. A plain progress
   * counter, credential-free.
   */
  unsigned int dtmf_played;
  /**
   * Total digits of the active sequence; `0` when no sequence is playing.
   * A plain progress counter, credential-free.
   */
  unsigned int dtmf_total;
  /**
   * `true` when M17 voice is available: the `m17` feature is compiled in
   * AND a working Codec 2 backend was found, probed against the current
   * [`iax_station_set_codec_dirs`] value (iax-f2b8 Task 5). Gate a UI's
   * M17 connect affordance on this rather than calling
   * [`iax_station_connect_m17`] speculatively.
   */
  bool m17_available;
  /**
   * `true` while an M17 session is live (mutually exclusive with an
   * active IAX2 call — see [`iax_station_connect_m17`]).
   */
  bool m17_active;
  /**
   * `true` when D-Star voice is available: the `dstar` feature is compiled
   * in AND a `ThumbDV` is attached RIGHT NOW (iax-4c8e). D-Star has no
   * software vocoder, so unlike [`Self::m17_available`] this tracks
   * HOTPLUG — it flips within ~500 ms of the dongle being plugged in or
   * pulled out. Gate a UI's D-Star affordance on this (grey it out when
   * `false`) rather than calling [`iax_station_connect_dstar`]
   * speculatively.
   */
  bool dstar_available;
  /**
   * `true` while a D-Star session is live — mutually exclusive with both
   * an active IAX2 call and an M17 session (see
   * [`iax_station_connect_dstar`]).
   */
  bool dstar_active;
  /**
   * `true` when System Fusion voice is available: the `ysf` feature is
   * compiled in AND a `ThumbDV` is attached right now. The same probe
   * [`Self::dstar_available`] reads — one dongle, one answer — so the two
   * flags move together and a UI can trust that they agree.
   */
  bool ysf_available;
  /**
   * `true` while a YSF link is live — mutually exclusive with an IAX2
   * call, an M17 session and a D-Star session (see
   * [`iax_station_connect_ysf`]). Transceive: key it with
   * `iax_station_set_ptt`, exactly as D-Star.
   */
  bool ysf_active;
  /**
   * `true` when NXDN voice is available: the `nxdn` feature is compiled in
   * AND a `ThumbDV` is attached right now. NXDN voice is AMBE+2 — the same
   * 49-bit frame YSF DN carries, off the same dongle — so this is the same
   * cached probe [`Self::dstar_available`] and [`Self::ysf_available`]
   * read, and all three move together.
   */
  bool nxdn_available;
  /**
   * `true` while an NXDN link is live — mutually exclusive with an IAX2
   * call, an M17 session, a D-Star session and a YSF link (see
   * [`iax_station_connect_nxdn`]).
   *
   * RECEIVE ONLY: there is no NXDN transmit path, so a key is refused
   * rather than queued and a UI must not offer PTT while this is set.
   *
   * Feature-INDEPENDENT, exactly as [`Self::dstar_active`] and
   * [`Self::ysf_active`] are: `astar-server` refuses remote keying while a
   * digital-voice link holds the dongle and must read that without
   * compiling the feature.
   */
  bool nxdn_active;
  /**
   * `true` when DMR voice is available: the `dmr` feature is compiled in
   * AND a `ThumbDV` is attached right now. DMR voice is AMBE+2 — the same
   * 49-bit frame YSF DN and NXDN carry, off the same dongle — so this is
   * the same cached probe [`Self::dstar_available`],
   * [`Self::ysf_available`] and [`Self::nxdn_available`] read, and all
   * four move together.
   */
  bool dmr_available;
  /**
   * `true` while a DMR link is live — mutually exclusive with an IAX2
   * call, an M17 session, a D-Star session, a YSF link and an NXDN link
   * (see [`iax_station_connect_dmr`]).
   *
   * RECEIVE ONLY: there is no DMR transmit path, so a key is refused
   * rather than queued and a UI must not offer PTT while this is set.
   *
   * Feature-INDEPENDENT, exactly as [`Self::dstar_active`],
   * [`Self::ysf_active`] and [`Self::nxdn_active`] are: `astar-server`
   * refuses remote keying while a digital-voice link holds the dongle and
   * must read that without compiling the feature.
   */
  bool dmr_active;
} IaxState;

/**
 * A drained lifecycle event. Caller-allocated; filled by
 * [`iax_station_next_event`]. The hangup *reason* string is not carried here
 * (it is secret-free but variable-length); callers that want it read it from a
 * status-text buffer in a future revision — the kind alone suffices for the
 * poll loop.
 */
typedef struct {
  /**
   * What happened.
   */
  IaxEventKind kind;
  /**
   * For [`IaxEventKind::RemotePtt`]: the new remote-keyed state.
   */
  bool remote_ptt;
} IaxEvent;

/**
 * One drained link lifecycle event. The node label is NOT embedded (variable
 * length): read it via [`iax_station_link_event_node`] immediately after a
 * successful drain, before the next [`iax_station_link_next_event`] call.
 */
typedef struct {
  /**
   * What happened ([`IaxLinkEventKind::None`] = nothing pending).
   */
  IaxLinkEventKind kind;
  /**
   * The link's opaque call id (matches the roster's `call`).
   */
  uint64_t call;
  /**
   * For [`IaxLinkEventKind::Keyed`]: the new keyed state.
   */
  bool keyed;
} IaxLinkEvent;

/**
 * `WireGuard` link-transport configuration passed to
 * [`iax_station_set_wireguard`]. All fields are **borrowed** `const char*`
 * (the library copies what it needs; the caller keeps ownership and may free
 * them right after the call returns).
 *
 * `endpoint`, `peer_public_key`, `tunnel_ip`, and `private_key` are required
 * (NULL → [`IAX_ERR_NULL`]). `allowed_ips` and `also_bind_udp` are optional
 * (NULL = none); `keepalive_secs` `0` selects the library default (25 s).
 *
 * The `private_key` is an **in-param** consumed into the engine at tunnel
 * build time via a one-shot resolver; it is never stored in any
 * config/snapshot/event/log type, never echoed back, and never appears in an
 * error string.
 */
typedef struct {
  /**
   * Peer (`WireGuard` server) endpoint `"host:port"` — an IP literal or a
   * DNS name. Required.
   */
  const char *endpoint;
  /**
   * The peer's public key, base64 (32 bytes encoded). Required.
   */
  const char *peer_public_key;
  /**
   * This station's tunnel address in IPv4 CIDR form (e.g. `"10.99.0.2/32"`).
   * Required; the tunnel-inner network is IPv4-only.
   */
  const char *tunnel_ip;
  /**
   * Comma-separated allowed-IPs CIDRs for the peer (advisory in the
   * userspace stack), or NULL for none. Whitespace around entries is
   * tolerated.
   */
  const char *allowed_ips;
  /**
   * Persistent keepalive interval in seconds, or `0` for the default (25).
   */
  uint16_t keepalive_secs;
  /**
   * This station's `WireGuard` private key, base64 (32 bytes encoded).
   * Required. Consumed; never stored, echoed, or logged.
   */
  const char *private_key;
  /**
   * Optional plain (non-tunnel) OS UDP listener address `"host:port"` the
   * engine binds ALONGSIDE the tunnel listener for direct/LAN peers, or
   * NULL for none.
   */
  const char *also_bind_udp;
} IaxWireguardConfig;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a station. Returns a non-NULL `IaxStation*` on success, or NULL if
 * `cfg` is NULL or a panic was caught. The returned handle must be released
 * with [`iax_station_free`]. The `cfg` pointer and its strings are borrowed
 * for the duration of the call only.
 */
IaxStation *iax_station_new(const IaxConfig *cfg);

/**
 * Free a station created by [`iax_station_new`]. NULL is a no-op. Tears down
 * any active call (via `Station`'s `Drop`).
 */
void iax_station_free(IaxStation *st);

/**
 * Manual / non-WT connect (the vendor-neutral generic IAX2 path). `dest`,
 * `calling`, and `name` are required `const char*`; `secret` may be NULL (the
 * configured guest secret is used). The `secret` is consumed immediately and
 * never stored or echoed. Returns [`IAX_OK`] or an `IAX_ERR_*` code.
 *
 * NOTE: this performs blocking network I/O (DNS resolve + dial); call it off
 * any UI thread.
 */
int iax_station_connect(IaxStation *st,
                        const char *dest,
                        const char *calling,
                        const char *secret,
                        const char *name);

/**
 * Web-Transceiver connect (the `AllStar` convenience path): mints a token from
 * the configured portal credentials, resolves `dest_node`, and dials. Requires
 * the three `portal_*` fields to have been set in [`IaxConfig`]; otherwise
 * returns [`IAX_ERR_PORTAL`]. Returns [`IAX_OK`] or an `IAX_ERR_*` code.
 */
int iax_station_connect_wt(IaxStation *st, const char *dest_node);

/**
 * Web-Transceiver connect to an EXPLICIT address (astar's manual-address path):
 * mints a token from the configured portal credentials exactly like
 * [`iax_station_connect_wt`], but dials `addr` (`host:port`, or a bare `host`
 * defaulting to the IAX2 port 4569; `host` may be an IP literal or a DNS name)
 * instead of the registrar-resolved node address. Use this for the
 * NAT-hairpin / localhost / LAN case where the registrar's public IP is
 * unreachable.
 *
 * `addr` must be non-NULL ([`IAX_ERR_NULL`]) and non-empty/parseable
 * ([`IAX_ERR_RESOLVE`]); for the registrar-resolved path use
 * [`iax_station_connect_wt`]. Requires the `portal_*` config fields
 * ([`IAX_ERR_PORTAL`] otherwise). Returns [`IAX_OK`] or an `IAX_ERR_*` code.
 */
int iax_station_connect_wt_addr(IaxStation *st, const char *dest_node, const char *addr);

/**
 * Validate the configured Web-Transceiver credentials WITHOUT placing a call:
 * run the portal login + WT-token mint from the held portal credentials, then
 * **discard** the minted token (it is never returned, stored, or logged). This
 * is the front-end "Test credentials" path; it opens **no** IAX call and **no**
 * UDP call socket.
 *
 * Takes **no secret argument** — it reuses the portal credentials supplied via
 * the three `portal_*` fields of [`IaxConfig`] at [`iax_station_new`]. Requires
 * those fields to have been set; otherwise returns [`IAX_ERR_PORTAL`]. Returns
 * [`IAX_OK`] on success, or an `IAX_ERR_*` code — [`IAX_ERR_PORTAL`] for a
 * login/token/network failure (the category is not carried across this ABI; the
 * message from [`iax_error_text`] is generic and secret-free).
 *
 * NOTE: this performs blocking network I/O (HTTPS to the portal); call it off
 * any UI thread.
 */
int iax_station_mint_token(IaxStation *st);

/**
 * Tear down any active call. Idempotent (no-op while idle). Returns
 * [`IAX_OK`], [`IAX_ERR_NULL`], or [`IAX_ERR_PANIC`].
 */
int iax_station_disconnect(IaxStation *st);

/**
 * Switch the operating mode (WT dial-out ↔ inbound Node). Entering Node mode
 * starts the listener (and fires registration if a registrar was configured
 * via [`iax_station_set_node_config`] and a resolver is set); leaving it tears
 * the node down and deregisters. Returns [`IAX_OK`] or an `IAX_ERR_*` code
 * ([`IAX_ERR_UNSUPPORTED`] for unsupported switches).
 *
 * NOTE: this performs blocking work (device + socket setup, registration);
 * call it off any UI thread.
 */
int iax_station_set_mode(IaxStation *st, IaxMode mode);

/**
 * Write the current operating mode into `out`. Returns [`IAX_OK`],
 * [`IAX_ERR_NULL`] (NULL `st`/`out`), or [`IAX_ERR_PANIC`].
 */
int iax_station_mode(IaxStation *st, IaxMode *out);

/**
 * Configure Node mode (listener bind, answer/auth policy, optional
 * register-as-node). Takes effect on the next switch to Node mode. The config
 * is **secret-free**; the registrar password is supplied only through the
 * resolver set by [`iax_station_set_credential_resolver`]. `cfg` and its
 * strings are borrowed for the duration of the call. Returns [`IAX_OK`],
 * [`IAX_ERR_NULL`] (NULL `st`/`cfg`, or `registrar` set without
 * `register_user`), [`IAX_ERR_RESOLVE`] (unparseable `bind`/`registrar`
 * address), [`IAX_ERR_UTF8`], or [`IAX_ERR_PANIC`].
 */
int iax_station_set_node_config(IaxStation *st, const IaxNodeConfig *cfg);

/**
 * Start the inbound IAX2 listener with the given node configuration.
 *
 * Binds the UDP listener to `cfg.bind` (defaulting to `0.0.0.0:4569` when
 * `bind` is NULL), and configures the auth/answer policy from `cfg`. The
 * station's operating mode is **not** changed — the listener runs
 * independently of the WT/Node mode flag. Call this to bring up the
 * always-on inbound path without switching modes.
 *
 * The registrar credential for any future authentication challenge is
 * supplied only via the resolver registered with
 * [`iax_station_set_credential_resolver`] — no credential is passed here.
 *
 * Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st` or `cfg`),
 * [`IAX_ERR_RESOLVE`] (unparseable `bind`), [`IAX_ERR_LISTEN`] (bind
 * failed — port in use, permission denied, etc.), [`IAX_ERR_UTF8`], or
 * [`IAX_ERR_PANIC`].
 *
 * NOTE: binds a UDP socket; call it off any UI thread.
 */
int iax_station_enable_inbound(IaxStation *st, const IaxNodeConfig *cfg);

/**
 * Stop the inbound listener started by [`iax_station_enable_inbound`] (or
 * by switching to Node mode). Idempotent — a no-op if the listener is not
 * running. The station's operating mode is **not** changed.
 *
 * Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_disable_inbound(IaxStation *st);

/**
 * Start outbound node registration using `cfg.registrar` / `cfg.register_user`
 * / `cfg.refresh_secs`. The registrar credential is resolved on demand via the
 * callback registered with [`iax_station_set_credential_resolver`] — no
 * credential is passed directly here.
 *
 * Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st`, `cfg`, or `registrar`/
 * `register_user` not set), [`IAX_ERR_RESOLVE`] (unparseable `registrar`),
 * [`IAX_ERR_UTF8`], or [`IAX_ERR_PANIC`].
 *
 * NOTE: opens a UDP socket; call it off any UI thread.
 */
int iax_station_register(IaxStation *st, const IaxNodeConfig *cfg);

/**
 * Stop outbound node registration. Sends REGREL to the registrar and joins the
 * registration thread. Idempotent — a no-op when not currently registered.
 *
 * Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_deregister(IaxStation *st);

/**
 * Register the credential resolver used to obtain secrets at runtime (e.g. the
 * registrar password for [`iax_station_set_node_config`]'s `registrar`). This
 * is the **only** channel for a secret across this ABI — secrets never appear
 * in any config struct, snapshot, event, or log. Returns [`IAX_OK`],
 * [`IAX_ERR_NULL`] (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_credential_resolver(IaxStation *st,
                                        IaxCredentialResolver resolver,
                                        void *user_data);

/**
 * Answer the pending inbound offer (Node/Manual). Returns
 * [`IAX_ERR_NOT_CONNECTED`] when not in Node mode or no offer is pending.
 */
int iax_station_answer(IaxStation *st);

/**
 * Reject the pending inbound offer (Node/Manual). Returns
 * [`IAX_ERR_NOT_CONNECTED`] when not in Node mode or no offer is pending.
 */
int iax_station_reject(IaxStation *st);

/**
 * Write the caller id of the most recent [`IaxEventKind::Incoming`] event into
 * the caller buffer `buf` of `len` bytes (NUL-terminated, truncate-safe).
 * Returns the byte length the full id needs (excluding the NUL) so the caller
 * can detect truncation, or a negative `IAX_ERR_*`. Pass `len == 0` to query
 * the size. The id is a node identifier — secret-free.
 */
int iax_station_incoming_from(IaxStation *st, char *buf, uintptr_t len);

/**
 * Set local transmit (PTT). Returns [`IAX_ERR_NOT_CONNECTED`] while idle.
 */
int iax_station_set_ptt(IaxStation *st, bool on);

/**
 * Send a single DTMF digit to the active call's peer (iax-0e9b). How the
 * digit is emitted follows the mode set via [`iax_station_set_dtmf_mode`]
 * (iax-7fff): by default one complete, fixed-duration in-band tone (~250 ms);
 * in [`IaxDtmfMode::Protocol`] one out-of-band `DTMF BEGIN`/`DTMF END` frame
 * pair. `digit` is an ASCII byte and must be one of the 16 DTMF keys
 * (`'0'..='9'`, `'*'`, `'#'`, `'A'..='D'`; iax-47ae); any other byte returns
 * [`IAX_ERR_INVALID_DIGIT`] without touching the call. Returns
 * [`IAX_ERR_NOT_CONNECTED`] while idle, [`IAX_ERR_NULL`] for a NULL handle.
 *
 * Input command only: nothing is stored, returned, or logged.
 */
int iax_station_send_dtmf(IaxStation *st, char digit);

/**
 * Send a multi-digit DTMF command to the active call as one engine-timed
 * sequence (iax-4b7a): ~250 ms tone + ~100 ms gap per digit, honoring the
 * mode set via [`iax_station_set_dtmf_mode`]. Validation is all-or-nothing:
 * `digits` must be a NUL-terminated string of the 16 DTMF keys only, or
 * [`IAX_ERR_INVALID_DIGIT`] is returned and nothing is sent (an empty string
 * is rejected the same way). The queue advances on [`iax_station_snapshot`]
 * polls; progress is [`IaxState::dtmf_played`] / [`IaxState::dtmf_total`].
 * Returns [`IAX_ERR_NOT_CONNECTED`] while idle (nothing queued),
 * [`IAX_ERR_DTMF_BUSY`] while a previous sequence is still playing,
 * [`IAX_ERR_NULL`] for a NULL handle or string.
 *
 * Input command only: nothing is stored beyond the queue, returned, or logged.
 */
int iax_station_send_dtmf_string(IaxStation *st, const char *digits);

/**
 * Drop the un-played remainder of an [`iax_station_send_dtmf_string`]
 * command (iax-4b7a). The digit currently sounding finishes its tone. Safe
 * to call when nothing is playing. Returns [`IAX_OK`] or [`IAX_ERR_NULL`].
 */
int iax_station_cancel_dtmf(IaxStation *st);

/**
 * Select how [`iax_station_send_dtmf`] emits digits (iax-7fff): an in-band
 * tone in the TX audio path ([`IaxDtmfMode::InBand`], the default) or
 * out-of-band IAX2 protocol frames ([`IaxDtmfMode::Protocol`]). The mode is
 * stored on the station and applies to the digits sent after the change;
 * setting it while idle is fine. Returns [`IAX_OK`], [`IAX_ERR_NULL`] for a
 * NULL handle, or [`IAX_ERR_PANIC`].
 */
int iax_station_set_dtmf_mode(IaxStation *st, IaxDtmfMode mode);

/**
 * Set the input (TX/mic) gain multiplier (clamped `[0.0, 4.0]`).
 */
int iax_station_set_input_gain(IaxStation *st, float gain);

/**
 * Set the output (RX/speaker) gain multiplier (clamped `[0.0, 4.0]`:
 * 100%-400% headroom for boosting a quiet station, iax-a4e7).
 */
int iax_station_set_output_gain(IaxStation *st, float gain);

/**
 * Toggle RX/output compression on the live/next call (iax-a4e7 PHASE 1):
 * automatic leveling of the RECEIVED audio, reusing the mic-path compressor
 * (makeup gain included) on the output bus, applied BEFORE the output gain
 * multiply so the 100%-400% output-gain range amplifies the already-leveled
 * signal. Shared across networks (output is listener-side). Takes effect
 * immediately on an active call's output bus. Returns [`IAX_OK`],
 * [`IAX_ERR_NULL`] (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_rx_compression(IaxStation *st, bool on);

/**
 * Set the RX/output compression strength (`level` clamped to `0.0..=1.0`):
 * `0.0` = light, `1.0` = most aggressive, default `0.90`. Takes effect
 * immediately when RX compression is enabled (iax-a4e7 PHASE 1). Returns
 * [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_rx_compression_level(IaxStation *st, float level);

/**
 * Configure the RX jitter buffer (iax-rxjb): whether received audio is played
 * out of the adaptive buffer at all, and the window (`min_ms`..=`max_ms`) its
 * depth may live in.
 *
 * The defaults are Asterisk `chan_iax2`'s — enabled, `min_ms` 40, `max_ms`
 * 200 — because the node at the other end of an `AllStarLink` call is Asterisk.
 * A larger `min_ms` buys fewer holes with more latency. Both bounds are
 * clamped to `0..=500` ms and a `max_ms` below `min_ms` is raised to meet it:
 * a setting is repaired, never refused. Takes effect immediately, mid-call,
 * with no reconnect; read the effective values back from `IaxState`'s
 * `rx_jb_enabled` / `rx_jb_min_ms` / `rx_jb_max_ms`. Returns [`IAX_OK`],
 * [`IAX_ERR_NULL`] (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_rx_jitter(IaxStation *st,
                              bool enabled,
                              unsigned int min_ms,
                              unsigned int max_ms);

/**
 * Toggle mic voice compression on the live/next call. Takes effect immediately
 * on an active call's capture lane. Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL
 * `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_compression(IaxStation *st, bool on);

/**
 * Set the neural mic noise-reduction strength (`level` clamped to
 * `0.0..=1.0`): `1.0` = full denoise (default), `0.0` = bypass. Takes effect
 * immediately.
 *
 * RNNoise has no strength parameter of its own, so this drives a
 * delay-compensated dry/wet mix. It has no effect while the classical
 * hum-filter-plus-gate chain is running — read `IaxState::denoise_chain` to
 * see which is live. Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st`), or
 * [`IAX_ERR_PANIC`].
 */
int iax_station_set_denoise_strength(IaxStation *st, float level);

/**
 * Set the mic voice-compression strength (`level` clamped to `0.0..=1.0`):
 * `0.0` = light, `1.0` = most aggressive, default `0.90`. Takes effect
 * immediately when compression is enabled. Returns [`IAX_OK`], [`IAX_ERR_NULL`]
 * (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_compression_level(IaxStation *st, float level);

/**
 * Set the TX trim gain (0.0..=4.0 clamped, default 1.0): the final output
 * stage after compression. Attenuates a hot mic that compression makeup gain
 * would otherwise keep loud; values above 1.0 boost (clamped at full scale).
 * Takes effect immediately on the live/next call. Returns [`IAX_OK`],
 * [`IAX_ERR_NULL`] (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_tx_trim(IaxStation *st, float gain);

/**
 * Set the live spectrum peak-hold decay in dB/SECOND (`db_per_sec` clamped to
 * `1.0..=500.0`, default `100.0`). Drives the fall-rate of the peak-held
 * spectrum bars shared by the mic monitor, the live-call TX, and the live-call
 * RX analyzers (iax-8616) — a single call scrubs every visible spectrum at
 * once. Applies to the analyzers that are currently live (the mic monitor if
 * monitoring, the active call's TX/RX if a call is up). Returns [`IAX_OK`],
 * [`IAX_ERR_NULL`] (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_spectrum_decay(IaxStation *st, float db_per_sec);

/**
 * Set the VOX pre-roll / look-back length in milliseconds (`ms` clamped to
 * `0..=250`, `0` = disabled, the default). When software VOX keys the call,
 * the engine flushes this much buffered mic audio ahead of the live stream so
 * the speech onset is not clipped. Takes effect immediately on the active
 * routed mic. Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st`), or
 * [`IAX_ERR_PANIC`].
 */
int iax_station_set_vox_preroll_ms(IaxStation *st, unsigned int ms);

/**
 * Toggle mic noise reduction (denoise) on the live/next call. Takes effect
 * immediately on an active call's capture lane. Returns [`IAX_OK`],
 * [`IAX_ERR_NULL`] (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_noise_reduction(IaxStation *st, bool on);

/**
 * Monitor THIS device (iax-2377): open the capture device and run the mic lane
 * WITHOUT a call so a front-end can preview / characterize the mic before
 * dialing. `input` is a capture-device name substring, or NULL for the system
 * default.
 *
 * Call it again to change mics: asking for a DIFFERENT resolved device stops
 * the running monitor and opens the new one, so a front-end's device picker
 * moves the stream and not just its label; asking for the device already
 * monitored is a no-op. The device is resolved before the running monitor is
 * touched, so a name that resolves to nothing returns an error and leaves the
 * current monitor running. Still call-safe: a no-op if a call is already
 * active (the device is already open on the call's mic lane).
 *
 * Stop it with [`iax_station_monitor_stop`]. Returns [`IAX_OK`],
 * [`IAX_ERR_AUDIO`] (device resolve/open failed), [`IAX_ERR_NULL`] (NULL `st`),
 * or [`IAX_ERR_PANIC`].
 *
 * NOTE: opens an audio device (blocking); call it off any UI thread.
 */
int iax_station_monitor_start(IaxStation *st, const char *input);

/**
 * Stop monitor mode and release the capture device. Idempotent (no-op if not
 * monitoring). Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st`), or
 * [`IAX_ERR_PANIC`].
 */
int iax_station_monitor_stop(IaxStation *st);

/**
 * Copy the live voice-band mic spectrum (iax-e73e) into the caller-allocated
 * `out` array (capacity `cap` floats) and return the number of bins written
 * (`0` while not monitoring), or a negative `IAX_ERR_*`. Each value is a
 * peak-held dBFS magnitude (`-120.0..=0.0`); the bins are log-spaced over the
 * voice band (~100 Hz..3.9 kHz). Poll-only (no callback); the front-end polls
 * ~20 Hz. The values are plain dBFS floats and carry no sensitive data. `out`
 * may be NULL only when `cap == 0` (a no-op that returns 0).
 *
 * Returns [`IAX_ERR_NULL`] (NULL `st`, or NULL `out` with `cap > 0`) or
 * [`IAX_ERR_PANIC`] on the boundary panic path.
 */
int iax_station_mic_spectrum(IaxStation *st, float *out, uintptr_t cap);

/**
 * Copy the live-call **TX** spectrum (iax-2b09) — the audio you are sending on
 * the active network call — into the caller-allocated `out` array (capacity
 * `cap` floats), returning the number of bins written (`0` with no active
 * call), or a negative `IAX_ERR_*`. Same bin contract as
 * [`iax_station_mic_spectrum`] (peak-held dBFS, log-spaced voice band,
 * `IAX_SPECTRUM_BINS` max). Poll-only; carries no sensitive data. `out` may be
 * NULL only when `cap == 0`.
 *
 * Returns [`IAX_ERR_NULL`] (NULL `st`, or NULL `out` with `cap > 0`) or
 * [`IAX_ERR_PANIC`] on the boundary panic path.
 */
int iax_station_tx_spectrum(IaxStation *st, float *out, uintptr_t cap);

/**
 * Copy the live-call **RX** spectrum (iax-2b09) — the audio received from the
 * far end on the active network call — into the caller-allocated `out` array
 * (capacity `cap` floats), returning the number of bins written (`0` with no
 * active call), or a negative `IAX_ERR_*`. Same bin contract as
 * [`iax_station_mic_spectrum`]. Poll-only; carries no sensitive data. `out` may
 * be NULL only when `cap == 0`.
 *
 * Returns [`IAX_ERR_NULL`] (NULL `st`, or NULL `out` with `cap > 0`) or
 * [`IAX_ERR_PANIC`] on the boundary panic path.
 */
int iax_station_rx_spectrum(IaxStation *st, float *out, uintptr_t cap);

/**
 * Characterize the monitored mic (iax-5fb6) and write the resulting
 * [`crate::IaxStation`]-side `MicProfile` as JSON into the caller buffer `buf`
 * of `len` bytes (NUL-terminated, truncate-safe). Returns the byte length the
 * full JSON needs (excluding the NUL) so the caller can size/retry, or a
 * negative `IAX_ERR_*`. Pass `len == 0` to query the size.
 *
 * Requires monitor mode to be running (see [`iax_station_monitor_start`]); call
 * after a few seconds of monitored silence. When not monitoring, writes an
 * empty string and returns 0. `harmonic_comb` toggles harmonic-aware notch
 * detection — **pass `false` for the default flat detector**; `true` enables a
 * learned-fundamental notch comb that catches rolled-off upper harmonics
 * (iax-5fb6; gated here so the comb stays off until validated).
 *
 * The JSON carries plain DSP numbers only (high-pass, notch frequencies/Q,
 * noise floor, gate threshold) — no credential fields.
 */
int iax_station_characterize(IaxStation *st, bool harmonic_comb, char *buf, uintptr_t len);

/**
 * Characterize the monitored mic with JSON options — the same buffer contract
 * and the same output JSON as [`iax_station_characterize`], but the caller
 * chooses the peak margin as well as the harmonic comb.
 *
 * `opts_json` is
 * `{"harmonic_comb":false,"peak_margin_db":12.0,"threshold_dbfs":-60.0}`. Every
 * key is optional and NULL or an empty string means "all defaults" (comb off,
 * 12 dB, no absolute threshold — exactly
 * `iax_station_characterize(st, false, …)`).
 *
 * The two detection knobs are alternatives, and `threshold_dbfs` wins:
 *
 * * `peak_margin_db` is RELATIVE — how far above the spectral-median noise
 *   floor a tone must stand to be worth notching. Raise it to leave quiet
 *   peaks alone. Clamped to 0–60 dB.
 * * `threshold_dbfs` is ABSOLUTE — a level, in the same sinusoid-normalised
 *   dBFS the live spectrum ([`iax_station_mic_spectrum`]) reports, that a peak
 *   must exceed. A tone drawn above that line on a spectrum display is above
 *   it for the detector too. Clamped to −140–0 dBFS. `null` (or an absent key)
 *   means "no absolute threshold": the relative margin decides.
 *
 * Either way, a mic with nothing above the bar characterizes as a PASS-THROUGH
 * profile (an empty notch list) that changes nothing in the mic lane. The
 * engine records the clamped values it actually used in the profile it
 * returns.
 *
 * Returns the byte length the full JSON needs (excluding the NUL), or a
 * negative `IAX_ERR_*`: [`IAX_ERR_NULL`] (NULL `st`), [`IAX_ERR_UTF8`]
 * (non-UTF-8 `opts_json`), [`IAX_ERR_IAX`] (unparsable options), or
 * [`IAX_ERR_PANIC`]. When not monitoring, writes an empty string and returns 0.
 *
 * The JSON carries plain DSP numbers only — no credential fields.
 */
int iax_station_characterize_opts(IaxStation *st, const char *opts_json, char *buf, uintptr_t len);

/**
 * Apply (or clear) a calibrated per-mic profile (iax-2095). `json` is a
 * `MicProfile` JSON string as produced by [`iax_station_characterize`] (or
 * persisted by the front-end), or NULL to CLEAR the profile back to the generic
 * noise reducer. A recalled profile rebuilds the live call's noise-reduction
 * comb (and seeds the next call). The JSON carries plain DSP numbers only
 * (high-pass, notch frequencies/Q, noise floor, gate threshold) — no credential
 * fields.
 *
 * Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st`), [`IAX_ERR_UTF8`] (non-UTF-8
 * `json`), [`IAX_ERR_AUDIO`] (malformed/invalid profile JSON), or
 * [`IAX_ERR_PANIC`].
 */
int iax_station_set_mic_profile(IaxStation *st, const char *json);

/**
 * Fill the caller-allocated `out` with the latest call state. Cheap; poll it.
 * Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st`/`out`), or [`IAX_ERR_PANIC`].
 */
int iax_station_snapshot(IaxStation *st, IaxState *out);

/**
 * Drain one queued lifecycle event into the caller-allocated `out`. When no
 * event is queued, `out.kind` is set to [`IaxEventKind::None`]. Returns
 * [`IAX_OK`], [`IAX_ERR_NULL`], or [`IAX_ERR_PANIC`].
 */
int iax_station_next_event(IaxStation *st, IaxEvent *out);

/**
 * Enumerate input device names, newline-joined, into the caller buffer `buf`
 * of `len` bytes (NUL-terminated, truncate-safe). Returns the number of bytes
 * the full list needs (excluding the NUL) so the caller can detect truncation,
 * or a negative `IAX_ERR_*` code. Pass `len == 0` to query the required size.
 */
int iax_station_list_inputs(IaxStation *st, char *buf, uintptr_t len);

/**
 * Enumerate output device names, newline-joined, into the caller buffer.
 * Same contract as [`iax_station_list_inputs`].
 */
int iax_station_list_outputs(IaxStation *st, char *buf, uintptr_t len);

/**
 * Set the capture/playback devices applied to the next connect. NULL selects
 * the system default for that direction. Returns [`IAX_OK`], [`IAX_ERR_NULL`]
 * (NULL `st`), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_devices(IaxStation *st, const char *input, const char *output);

/**
 * Size in bytes of [`IaxState`] as this library lays it out.
 *
 * Every foreign binding mirrors `IaxState` by hand (ctypes `Structure`, a
 * Swift `struct`, …) and `iax_station_snapshot` writes `size_of::<IaxState>()`
 * bytes into the caller's buffer. A mirror that has fallen behind is therefore
 * not a cosmetic mismatch but a **heap overflow** in the caller, plus garbage
 * reads from every field past the first divergence. Bindings should assert
 * their mirror's size against this at load time so the drift fails loudly and
 * immediately instead of corrupting memory. Carries no state and no secret.
 */
uintptr_t iax_state_size(void);

/**
 * Size in bytes of [`IaxEvent`] as this library lays it out. Same contract as
 * [`iax_state_size`]: `iax_station_next_event` fills a caller-allocated
 * `IaxEvent`, so a stale mirror overflows the caller's buffer.
 */
uintptr_t iax_event_size(void);

/**
 * Map an `IAX_ERR_*` code (or [`IAX_OK`]) to a `'static`, NUL-terminated,
 * human-readable C string. The returned pointer is owned by the library and
 * must **never** be freed by the caller. The strings are generic and
 * secret-free.
 */
const char *iax_error_text(int code);

/**
 * Connect a node link: resolve `node` via the `AllStar` registrar and dial it
 * in `mode`. `secret` is consumed at dial time and never stored. Returns
 * [`IAX_OK`] or a negative `IAX_ERR_*` ([`IAX_ERR_RESOLVE`] /
 * [`IAX_ERR_LINK`] / [`IAX_ERR_AUDIO`]).
 */
int iax_station_link_connect(IaxStation *st,
                             const char *node,
                             IaxLinkMode mode,
                             const char *caller_id,
                             const char *secret,
                             bool permanent);

/**
 * [`iax_station_link_connect`] with an explicit `host:port` address instead
 * of registrar resolution (private nodes / test rigs).
 */
int iax_station_link_connect_at(IaxStation *st,
                                const char *node,
                                const char *addr,
                                IaxLinkMode mode,
                                const char *caller_id,
                                const char *secret,
                                bool permanent);

/**
 * Tear a link down by node label. Returns [`IAX_OK`] or [`IAX_ERR_LINK`].
 */
int iax_station_link_disconnect(IaxStation *st, const char *node);

/**
 * Change a link's mode by node label (Transceive routes the default mic so
 * the link is immediately key-able). Returns [`IAX_OK`] or [`IAX_ERR_LINK`].
 */
int iax_station_link_set_mode(IaxStation *st, const char *node, IaxLinkMode mode);

/**
 * Key / unkey a link by node label (refused for non-transmit modes).
 * Returns [`IAX_OK`] or [`IAX_ERR_LINK`].
 */
int iax_station_link_key(IaxStation *st, const char *node, bool on);

/**
 * Write the live link roster as JSON (`{"links":[{"call":..,"node":"..",
 * "mode":"..","state":"..","keyed":..}]}`) into the caller buffer.
 * Same contract as [`iax_station_list_inputs`]: NUL-terminated + truncate-
 * safe; returns the byte length the full JSON needs (a `len == 0` call is a
 * sizing query), or a negative `IAX_ERR_*`.
 */
int iax_station_link_roster_json(IaxStation *st, char *buf, uintptr_t len);

/**
 * Write who has keyed up on the live digital link as a JSON array, newest
 * first (`[{"callsign":"..","network":"m17","age_ms":1234}]`, `[]` when
 * nothing has been heard) into the caller buffer. Same contract as
 * [`iax_station_link_roster_json`]: NUL-terminated + truncate-safe; returns
 * the byte length the full JSON needs (a `len == 0` call is a sizing query),
 * or a negative `IAX_ERR_*`.
 */
int iax_station_heard_json(IaxStation *st, char *buf, uintptr_t len);

/**
 * Drain the next pending link lifecycle event. Returns 1 and fills `out`
 * when an event was pending (read the node label via
 * [`iax_station_link_event_node`] before the next drain), 0 when none, or a
 * negative `IAX_ERR_*`.
 */
int iax_station_link_next_event(IaxStation *st, IaxLinkEvent *out);

/**
 * Node label of the most recently drained link event (NUL-terminated into
 * the caller buffer; same contract as [`iax_station_incoming_from`]).
 */
int iax_station_link_event_node(IaxStation *st, char *buf, uintptr_t len);

/**
 * Detail text of the most recent failed call on this station (NUL-terminated
 * into the caller buffer; same query-then-fill contract as
 * [`iax_station_list_inputs`] — pass `len == 0` to learn the required size).
 *
 * `IAX_ERR_*` codes are coarse on purpose: [`IAX_ERR_AUDIO`] alone covers a
 * device that vanished, a config the device will not accept, and a cpal
 * stream that failed to build. The code says which family failed; this says
 * what happened — "device not found: KT USB Audio", "stream build failed:
 * The requested device is no longer available", and so on.
 *
 * Empty when no call has failed yet. It is not cleared on success, so read
 * it immediately after a negative return rather than treating it as current
 * state.
 *
 * Secret-free: it is `StationError`'s own `Display`, which renders portal
 * and resolve failures as generic text with no underlying source precisely
 * so a credential embedded in one can never reach a caller.
 */
int iax_station_last_error(IaxStation *st, char *buf, uintptr_t len);

/**
 * Route the whole engine — outgoing dials, the inbound listener, and outbound
 * registration — through one shared userspace `WireGuard` tunnel (iax-912e).
 * Call BEFORE connect/enable-inbound: the transport is immutable while a
 * session is up (switching = disconnect/reconnect, then set again). Never
 * calling this is byte-identical to plain OS UDP.
 *
 * A NULL `cfg` clears the transport back to plain OS UDP (the inverse
 * operation, same immutability rule). `cfg` and its strings are borrowed for
 * the duration of the call; the `private_key` is consumed via a one-shot
 * resolver and never stored (see [`IaxWireguardConfig`]).
 *
 * Returns [`IAX_OK`], [`IAX_ERR_NULL`] (NULL `st`, or a required field NULL),
 * [`IAX_ERR_UTF8`], [`IAX_ERR_RESOLVE`] (unresolvable `endpoint` /
 * unparseable `also_bind_udp`), [`IAX_ERR_LINK`] (bad key/CIDR),
 * [`IAX_ERR_ALREADY_CONNECTED`] (a call is pooled), or [`IAX_ERR_PANIC`].
 */
int iax_station_set_wireguard(IaxStation *st, const IaxWireguardConfig *cfg);

/**
 * Connect to an M17 reflector (iax-f2b8 Task 4/5): resolves `host`/`port`
 * and opens a full-transceive session on `module`, mutually exclusive with
 * an active IAX2 call. See [`astar_station::Station::m17_connect`] for
 * the full contract (module case-folding, codec-dir search, exclusivity).
 *
 * `host` and `callsign` are required (NULL/non-UTF-8 → [`IAX_ERR_NULL`] /
 * [`IAX_ERR_UTF8`]). `module` must be a single ASCII byte; a non-ASCII byte
 * is rejected here with [`IAX_ERR_M17`] before it ever reaches the station
 * — the remaining `A`-`Z` validation (and an empty `callsign`) is caught by
 * the station and also maps to [`IAX_ERR_M17`]. Returns [`IAX_OK`],
 * [`IAX_ERR_ALREADY_CONNECTED`] (an IAX2 call is live), [`IAX_ERR_M17`], or
 * [`IAX_ERR_PANIC`].
 *
 * NOTE: this performs blocking work (device resolve, socket bind, session
 * spawn); call it off any UI thread.
 */
int iax_station_connect_m17(IaxStation *st,
                            const char *host,
                            uint16_t port,
                            char module,
                            const char *callsign);

/**
 * Disconnect the live M17 session, if any (iax-f2b8 Task 4/5). Idempotent —
 * a no-op while idle. Returns [`IAX_OK`], [`IAX_ERR_NULL`], or
 * [`IAX_ERR_PANIC`].
 */
int iax_station_m17_disconnect(IaxStation *st);

/**
 * Write the live M17 session's state as JSON into the caller buffer `buf` of
 * `len` bytes (NUL-terminated, truncate-safe; same contract as
 * [`iax_station_dstar_state`] — returns the byte length the full JSON needs,
 * excluding the NUL, so a `len == 0` call is a sizing query).
 *
 * ```json
 * {"link":"linked","receiving":true,"ptt":false,"talker":"N0CALL"}
 * ```
 *
 * `link` is one of `idle`/`linking`/`linked`/`failed` — the same vocabulary
 * D-Star and YSF use, minus the `unlinking` M17 has no state for.
 *
 * `talker` is the source callsign from the LSF of the most recently heard
 * stream, `null` until one arrives, and it PERSISTS past end-of-stream — it
 * is "most recently heard", not "transmitting right now". `receiving` is the
 * field that says whether a transmission is in progress.
 *
 * Every field is credential-free: one callsign and two flags. The
 * network-agnostic state (the level meters, the call status) is in
 * [`IaxSnapshot`] — poll that on a metering tick and call this only for the
 * talker.
 *
 * Writes `{}` when no session is active or the `m17` feature isn't compiled
 * in. Returns [`IAX_ERR_NULL`] if `st` is NULL, or [`IAX_ERR_PANIC`].
 */
int iax_station_m17_state(IaxStation *st, char *buf, uintptr_t len);

/**
 * Set extra directories to search for a runtime `libcodec2`, ahead of the
 * hard-coded system paths (iax-f2b8 Task 4/5). `dirs` is a single
 * NUL-terminated string of `':'`-separated filesystem paths (e.g.
 * `"/opt/app/lib:/usr/local/lib"`); NULL or empty clears the list back to
 * the system search paths only. Call before [`iax_station_connect_m17`] —
 * it does not affect a session already in progress. Returns [`IAX_OK`],
 * [`IAX_ERR_UTF8`] (non-UTF-8 `dirs`), [`IAX_ERR_NULL`] (NULL `st`), or
 * [`IAX_ERR_PANIC`].
 */
int iax_station_set_codec_dirs(IaxStation *st, const char *dirs);

/**
 * Connect to a D-Star `DExtra` reflector (iax-a9d4 built RX, iax-2f6b added
 * TX): resolves `host`/`port` and opens a full-transceive session on
 * `module`, mutually exclusive with both an active IAX2 call and a live M17
 * session. See [`astar_station::Station::dstar_connect`] for the full
 * contract.
 *
 * D-Star is HARDWARE-ONLY: the vocoder is a DVSI `ThumbDV`, with no software
 * fallback, so this fails when no dongle is attached. Poll
 * [`IaxSnapshot::dstar_available`] and offer the affordance only when it is
 * `true`, rather than calling this speculatively.
 *
 * `reflector_callsign` names the DESTINATION reflector as the directories
 * list it (`"XLX836"`, `"XRF757"`) and fills the transmitted RF header's
 * `RPT1`/`RPT2` — the fields that say where a transmission is going. Pass
 * NULL to derive it from `host`'s first DNS label (`xlx836.…` → `XLX836`,
 * which goes on the `DExtra` wire as `XRF836`), which is right for every
 * reflector reached by its published hostname. A front-end that connects by
 * bare IP address should pass it, because there is nothing to derive from
 * and the header then transmits with `RPT1`/`RPT2` blank — no destination or
 * repeater identity at all.
 *
 * `host` and `callsign` are required (NULL/non-UTF-8 → [`IAX_ERR_NULL`] /
 * [`IAX_ERR_UTF8`]); `reflector_callsign` is optional, but a non-NULL,
 * non-UTF-8 one is [`IAX_ERR_UTF8`]. `module` must be a single ASCII byte; a non-ASCII byte
 * is rejected here with [`IAX_ERR_DSTAR`] before it reaches the station —
 * the remaining `A`-`Z` validation (and an empty `callsign`) is caught by
 * the station and also maps to [`IAX_ERR_DSTAR`]. Returns [`IAX_OK`],
 * [`IAX_ERR_ALREADY_CONNECTED`] (an IAX2 call or M17 session is live),
 * [`IAX_ERR_DSTAR`], or [`IAX_ERR_PANIC`].
 *
 * NOTE: this performs blocking work — a serial-port scan plus, per candidate
 * port and baud rate, an open and an eight-transaction dongle init, then a
 * socket bind and session spawn. It can take on the order of a second. Call
 * it off any UI thread.
 */
int iax_station_connect_dstar(IaxStation *st,
                              const char *host,
                              uint16_t port,
                              char module,
                              const char *callsign,
                              const char *reflector_callsign);

/**
 * Disconnect the live D-Star session, if any (iax-4c8e). Idempotent — a
 * no-op while idle. Returns [`IAX_OK`], [`IAX_ERR_NULL`], or
 * [`IAX_ERR_PANIC`].
 */
int iax_station_dstar_disconnect(IaxStation *st);

/**
 * Write the live D-Star session's state as JSON into the caller buffer `buf`
 * of `len` bytes (NUL-terminated, truncate-safe; same contract as
 * [`iax_station_list_inputs`] — returns the byte length the full JSON needs,
 * excluding the NUL, so a `len == 0` call is a sizing query).
 *
 * Carries the D-Star-shaped state that has no equivalent in
 * [`IaxSnapshot`]'s network-agnostic fields:
 *
 * ```json
 * {"link":"linked","talker":"AJ7HR","slow_text":"hi","backend":"thumbdv",
 *  "tx_capable":true,"ptt":false,"tx_db":-60.0,"rx_db":-31.2,"input_db":-45.0}
 * ```
 *
 * `link` is one of `idle`/`linking`/`linked`/`unlinking`/`failed`; `backend`
 * is `thumbdv` (or `soft`, which D-Star never uses today). `talker` and
 * `slow_text` are `null` until a header / a complete slow-data message has
 * been received, and then PERSIST past end-of-transmission — they are
 * "most recently heard", not "currently transmitting". Every field is
 * credential-free: callsigns and levels only.
 *
 * Writes `{}` when no session is active or the `dstar` feature isn't
 * compiled in. Returns [`IAX_ERR_NULL`] if `st` is NULL, or
 * [`IAX_ERR_PANIC`].
 *
 * The three level fields duplicate [`IaxSnapshot`]'s `tx_db`/`rx_db`/
 * `input_db`, which mirror the active session whatever its network — read
 * them from the snapshot on a metering tick and call this only when the UI
 * needs the D-Star-specific fields.
 */
int iax_station_dstar_state(IaxStation *st, char *buf, uintptr_t len);

/**
 * Link to a `YSFReflector` and decode the audio on it (astar-e7b3 §2).
 *
 * `host` is `host:port` — YSF publishes a port per reflector and has no
 * conventional default, so there is nothing sensible to assume. `options`
 * is the YCS room request; pass NULL for a plain reflector.
 *
 * YSF is HARDWARE-ONLY for the same reason D-Star is — the vocoder is
 * AMBE+2 on a DVSI `ThumbDV`. Poll [`IaxSnapshot::ysf_available`] and offer
 * the affordance only when it is `true`, rather than calling this
 * speculatively.
 *
 * `host` and `callsign` are required (NULL/non-UTF-8 → [`IAX_ERR_NULL`] /
 * [`IAX_ERR_UTF8`]); `options` is optional, but a non-NULL, non-UTF-8 one is
 * [`IAX_ERR_UTF8`]. Returns [`IAX_OK`], [`IAX_ERR_ALREADY_CONNECTED`] (any
 * other network is live), [`IAX_ERR_YSF`], or [`IAX_ERR_PANIC`].
 *
 * NOTE: this performs blocking work — a serial-port scan plus, per candidate
 * port and baud rate, an open and an eight-transaction dongle init, then a
 * socket bind and thread spawn. It can take on the order of a second. Call
 * it off any UI thread.
 */
int iax_station_connect_ysf(IaxStation *st,
                            const char *host,
                            const char *callsign,
                            const char *options);

/**
 * Disconnect the live YSF link, if any. Idempotent — a no-op while idle.
 * Returns [`IAX_OK`], [`IAX_ERR_NULL`], or [`IAX_ERR_PANIC`].
 */
int iax_station_ysf_disconnect(IaxStation *st);

/**
 * Write the live YSF link's state as JSON into the caller buffer `buf` of
 * `len` bytes (NUL-terminated, truncate-safe; same contract as
 * [`iax_station_dstar_state`] — returns the byte length the full JSON needs,
 * excluding the NUL, so a `len == 0` call is a sizing query).
 *
 * ```json
 * {"link":"linked","last_heard":"AJ7HR","frames_rx":412,"receiving":true,
 *  "unsupported_mode":null,"backend":"thumbdv","ptt":false,"rx_db":-31.2}
 * ```
 *
 * `link` is one of `idle`/`linking`/`linked`/`unlinking`/`failed`.
 * `last_heard` is read from the frame header in clear, needs no vocoder, and
 * PERSISTS past end-of-transmission — it is "most recently heard", not
 * "currently transmitting"; `receiving` is the one that says whether a
 * transmission is in progress. `frames_rx` is a liveness counter: a link
 * that is up and silent and one that is receiving look identical from
 * `link` alone.
 *
 * `unsupported_mode` is the field worth wiring into the UI. It is `null`
 * normally, and otherwise names a mode astar could not decode — `voice-fr`
 * (VW, full-rate voice) or `data-fr`. astar decodes DN only, and a reflector
 * carrying VW would otherwise be indistinguishable from a broken one:
 * silence, with nothing saying why. Show it.
 *
 * Every field is credential-free: callsigns and counters only.
 *
 * Writes `{}` when no link is active or the `ysf` feature isn't compiled in.
 * Returns [`IAX_ERR_NULL`] if `st` is NULL, or [`IAX_ERR_PANIC`].
 */
int iax_station_ysf_state(IaxStation *st, char *buf, uintptr_t len);

/**
 * Link to an `NXDNReflector` and decode the audio on it (iax-b9c2).
 *
 * `host` is `host:port` — NXDN reflectors publish a port per reflector, so
 * there is nothing conventional to assume. `callsign` is this station's own,
 * sent in the registration poll; `radio_id` is its registered NXDN number
 * and `talkgroup` the TG to join. Both are plain scalars here: NXDN
 * addresses stations by NUMBER, and parsing an operator's typing into one is
 * the caller's job, not the ABI's.
 *
 * NXDN is HARDWARE-ONLY for the same reason D-Star and YSF are — the vocoder
 * is AMBE+2 on a DVSI `ThumbDV`. Poll [`IaxState::nxdn_available`] and offer
 * the affordance only when it is `true`, rather than calling this
 * speculatively.
 *
 * **RECEIVE ONLY today.** There is no NXDN transmit path: a key-down is
 * REFUSED, not queued, so a UI must not offer PTT while this link is live.
 * See `astar_console::nxdn`'s Transmit section for why a refusal beats a key
 * that silently does nothing.
 *
 * `host` and `callsign` are required (NULL/non-UTF-8 → [`IAX_ERR_NULL`] /
 * [`IAX_ERR_UTF8`]). A zero `radio_id` or `talkgroup` is [`IAX_ERR_NXDN`]:
 * zero is what an unset field looks like, not a registration. Returns
 * [`IAX_OK`], [`IAX_ERR_ALREADY_CONNECTED`] (any other network is live),
 * [`IAX_ERR_NXDN`], or [`IAX_ERR_PANIC`].
 *
 * NOTE: this performs blocking work — a serial-port scan plus, per candidate
 * port and baud rate, an open and a multi-transaction dongle init, then a
 * socket bind and thread spawn. It can take on the order of a second. Call
 * it off any UI thread.
 */
int iax_station_connect_nxdn(IaxStation *st,
                             const char *host,
                             const char *callsign,
                             uint16_t radio_id,
                             uint16_t talkgroup);

/**
 * Disconnect the live NXDN link, if any. Idempotent — a no-op while idle.
 * Returns [`IAX_OK`], [`IAX_ERR_NULL`], or [`IAX_ERR_PANIC`].
 */
int iax_station_nxdn_disconnect(IaxStation *st);

/**
 * Write the live NXDN link's state as JSON into the caller buffer `buf` of
 * `len` bytes (NUL-terminated, truncate-safe; same contract as
 * [`iax_station_dstar_state`] — returns the byte length the full JSON needs,
 * excluding the NUL, so a `len == 0` call is a sizing query).
 *
 * ```json
 * {"link":"linked","last_heard":"4242","last_heard_id":4242,"frames_rx":97,
 *  "receiving":true,"backend":"thumbdv","ptt":false,"rx_db":-31.2}
 * ```
 *
 * `link` is one of `idle`/`linking`/`linked`/`unlinking`/`failed`.
 *
 * `last_heard` is a NUMBER rendered as a string, not a callsign: an `NXDND`
 * datagram carries `srcId` and no callsign at all, so identifying the sender
 * is a directory lookup astar does not hold. `last_heard_id` is that same id
 * unformatted, for a caller that has a directory. Both are read from the
 * header in clear, need no vocoder, and PERSIST past end-of-transmission —
 * they are "most recently heard", not "currently transmitting". `receiving`
 * is the one that says whether a transmission is in progress, and
 * `frames_rx` is a liveness counter: a link that is up and silent and one
 * that is receiving look identical from `link` alone.
 *
 * `ptt` is always `false`: NXDN is receive-only today and a key is refused.
 *
 * Every field is credential-free: numbers, counters and a level.
 *
 * Writes `{}` when no link is active or the `nxdn` feature isn't compiled
 * in. Returns [`IAX_ERR_NULL`] if `st` is NULL, or [`IAX_ERR_PANIC`].
 */
int iax_station_nxdn_state(IaxStation *st, char *buf, uintptr_t len);

/**
 * Link to a DMR master's talkgroup and decode the audio on it (iax-d4f7).
 *
 * `system` is a network SLUG — `tgif`, `brandmeister`, … — not a hostname:
 * each network has its own rules, and a near-miss that resolved to the wrong
 * one would put the operator on the wrong system under their own registered
 * ID, so an unknown slug is refused rather than guessed. `host`/`port` are
 * that network's master. `radio_id` is the station's radioid.net
 * registration, `talkgroup` the room and `timeslot` 1 or 2. DMR addresses
 * stations by NUMBER — a `DMRD` carries `srcId` and no callsign at all — so
 * `callsign` rides only in the login's config packet.
 *
 * # The password
 * `password` is the master password. It is copied out of the caller's buffer
 * into an owned `String` at the top of this function, moved onward into the
 * link, spent on one login digest and dropped. Nothing on the station, in a
 * snapshot, in an error, in the state JSON or in a log ever holds it — see
 * [`iax_station_dmr_state`], whose document has no field it could occupy.
 * The caller's own buffer is the caller's to scrub.
 *
 * DMR is HARDWARE-ONLY for the same reason D-Star, YSF and NXDN are — the
 * vocoder is AMBE+2 on a DVSI `ThumbDV`. Poll [`IaxState::dmr_available`] and
 * offer the affordance only when it is `true`, rather than calling this
 * speculatively.
 *
 * **RECEIVE ONLY today.** There is no DMR transmit path: a key-down is
 * REFUSED, not queued, so a UI must not offer PTT while this link is live.
 * See `astar_console::dmr`'s Transmit section for why a refusal beats a key
 * that silently does nothing.
 *
 * `system`, `host`, `callsign` and `password` are required (NULL/non-UTF-8 →
 * [`IAX_ERR_NULL`] / [`IAX_ERR_UTF8`]; a NULL password is a caller bug, not
 * an empty password). Returns [`IAX_OK`], [`IAX_ERR_ALREADY_CONNECTED`] (any
 * other network is live), [`IAX_ERR_DMR`] for an unknown or ungated network,
 * a zero/over-wide `radio_id`, an empty `callsign` or `password`, a zero
 * `talkgroup`, a `timeslot` that is not 1 or 2, or a login the master
 * refused, or [`IAX_ERR_PANIC`].
 *
 * NOTE: this performs blocking work — a serial-port scan plus, per candidate
 * port and baud rate, an open and a multi-transaction dongle init, then a
 * socket bind and a multi-round-trip login to the master. It can take
 * several seconds. Call it off any UI thread.
 */
int iax_station_connect_dmr(IaxStation *st,
                            const char *system,
                            const char *host,
                            uint16_t port,
                            uint32_t radio_id,
                            const char *callsign,
                            uint32_t talkgroup,
                            uint8_t timeslot,
                            const char *password);

/**
 * Disconnect the live DMR link, if any. Idempotent — a no-op while idle.
 * Returns [`IAX_OK`], [`IAX_ERR_NULL`], or [`IAX_ERR_PANIC`].
 */
int iax_station_dmr_disconnect(IaxStation *st);

/**
 * Write the live DMR link's state as JSON into the caller buffer `buf` of
 * `len` bytes (NUL-terminated, truncate-safe; same contract as
 * [`iax_station_nxdn_state`] — returns the byte length the full JSON needs,
 * excluding the NUL, so a `len == 0` call is a sizing query).
 *
 * ```json
 * {"link":"linked","failure":null,"last_heard":"4242","last_heard_id":4242,
 *  "talkgroup":31313,"timeslot":2,"frames_rx":97,"receiving":true,
 *  "backend":"thumbdv","ptt":false,"rx_db":-31.2}
 * ```
 *
 * `link` is one of `idle`/`logging_in`/`authenticating`/`configuring`/
 * `linked`/`closing`/`failed` — a homebrew login is a conversation, and an
 * operator watching it stall is owed which round trip stalled.
 *
 * `failure` says where a failed link failed — `login`/`auth`/`config`/
 * `session`/`closed`/`timeout` — and is `null` while it has not. "Your
 * password is wrong" (`auth`) and "your ID is not allowed here" (`login`) are
 * the two an operator can act on; show it.
 *
 * `last_heard` is a NUMBER rendered as a string, not a callsign: a `DMRD`
 * datagram carries `srcId` and no callsign at all, so identifying the sender
 * is a directory lookup astar does not hold. `last_heard_id` is that same id
 * unformatted, for a caller that has a directory. Both PERSIST past
 * end-of-transmission — they are "most recently heard", not "currently
 * transmitting". `receiving` is the one that says whether a transmission is
 * in progress, and `frames_rx` is a liveness counter: a link that is up and
 * silent and one that is receiving look identical from `link` alone.
 *
 * `timeslot` is the slot NUMBER, 1 or 2 (the engine's own `ts1`/`ts2` label
 * is not what an operator reads).
 *
 * `ptt` is always `false`: DMR is receive-only today and a key is refused.
 *
 * Every field is credential-free: numbers, counters and a level. There is no
 * password field, and `iax_station_connect_dmr`'s never reaches here.
 *
 * Writes `{}` when no link is active or the `dmr` feature isn't compiled in.
 * Returns [`IAX_ERR_NULL`] if `st` is NULL, or [`IAX_ERR_PANIC`].
 */
int iax_station_dmr_state(IaxStation *st, char *buf, uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ASTAR_H */
