#ifndef ASTARSERIAL_H
#define ASTARSERIAL_H

#pragma once

/* Generated by cbindgen. DO NOT EDIT. Regenerate with scripts/check-cbindgen-serial.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success.
 */
#define IAX_OK 0

/**
 * A Rust panic was caught at the boundary.
 */
#define IAX_ERR_PANIC -1

/**
 * A NULL handle or out-pointer argument.
 */
#define IAX_ERR_NULL -2

/**
 * The serial port could not be opened (bad path, busy, permissions).
 */
#define IAX_ERR_OPEN -3

/**
 * A serial read/write failed during a tick (e.g. device unplugged).
 */
#define IAX_ERR_SERIAL -4

/**
 * Autodetect found no matching device.
 */
#define IAX_ERR_NO_DEVICE -5

/**
 * A caller buffer was too small.
 */
#define IAX_ERR_BUFFER -6

/**
 * Which transport reaches the radio interface's modem-control lines.
 *
 * `Usb` is the raw-USB backend (no tty, no dext): sandbox/MAS- and iOS-eligible,
 * the only path that works inside the App Store sandbox, and what astar's own
 * clients select. `Tty` is the OS serial tty (`/dev/cu.*`), which on macOS needs
 * the `CH34x` dext.
 *
 * `Tty` is the C enum's **zero value**, so a zero-initialized [`IaxSerialConfig`]
 * selects the tty path. That is an ABI fact, not a recommendation: opening a USB
 * radio interface's tty asserts RTS, and RTS is the radio-key line. Callers should
 * set this field explicitly rather than relying on zero-init.
 */
typedef enum {
  IaxSerialTransport_Tty = 0,
  IaxSerialTransport_Usb = 1,
} IaxSerialTransport;

/**
 * Operator-key INPUT line.
 */
typedef enum {
  IaxKeyLine_Cts = 0,
  IaxKeyLine_Dcd = 1,
  IaxKeyLine_Dsr = 2,
  IaxKeyLine_Ri = 3,
} IaxKeyLine;

/**
 * Radio-key OUTPUT line.
 */
typedef enum {
  IaxRadioLine_Rts = 0,
  IaxRadioLine_Dtr = 1,
} IaxRadioLine;

/**
 * What drives the radio key while receiving.
 */
typedef enum {
  IaxRxKeyMode_RemotePtt = 0,
  IaxRxKeyMode_RxActivity = 1,
} IaxRxKeyMode;

/**
 * Opaque serial-client handle (a `Box<IaxSerial>` behind a raw pointer).
 *
 * All hardware I/O runs on an internal worker thread ([`PttAgent`], iax-239a):
 * [`iax_serial_ptt_tick`] is a non-blocking mailbox exchange, so a wedged USB
 * transfer (device re-enumerated mid-flight) can never park the caller —
 * the tick reports `IAX_ERR_SERIAL` once the worker's heartbeat goes stale.
 *
 * **Not thread-safe.** Use one `IaxSerial*` from a single thread at a time:
 * concurrent calls on the same handle are undefined behavior. (This differs
 * from `IaxStation*`, which is internally synchronized.)
 */
typedef struct IaxSerial IaxSerial;

/**
 * Serial client configuration. The only string is `port_path`; carries no credentials.
 */
typedef struct {
  /**
   * Serial device path; NULL = autodetect. Ignored when `transport` is `Usb`.
   */
  const char *port_path;
  /**
   * Which transport reaches the modem-control lines. Set it explicitly:
   * `Usb` for the raw-USB / sandbox-eligible backend, `Tty` for the OS
   * serial device. Zero-init lands on `Tty` — see [`IaxSerialTransport`].
   */
  IaxSerialTransport transport;
  /**
   * Operator-key input line.
   */
  IaxKeyLine key_line;
  /**
   * `true`: input asserted == keyed.
   */
  bool key_active_high;
  /**
   * Radio-key output line.
   */
  IaxRadioLine radio_line;
  /**
   * `true`: assert output == key the radio.
   */
  bool radio_active_high;
  /**
   * Key de-glitch window in ms; 0 = no debounce.
   */
  uint32_t cts_debounce_ms;
  /**
   * What drives the radio key while receiving.
   */
  IaxRxKeyMode rx_mode;
  /**
   * `RxActivity`: level (dBFS) strictly above this counts as active.
   */
  float rx_floor_db;
  /**
   * `RxActivity`: keep the radio keyed this long (ms) after audio stops.
   */
  uint32_t rx_hang_ms;
} IaxSerialConfig;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Map an `IAX_ERR_*` code (or [`IAX_OK`]) to a `'static`, NUL-terminated,
 * no-credential C string. The pointer is owned by the library; never free it.
 */
const char *iax_serial_error_text(int code);

/**
 * Open the serial port (explicit `port_path` or autodetect when NULL), clear
 * the radio line, and build the keying bridge. Returns NULL on any failure
 * (NULL config, no device, port busy, bad path, non-UTF-8 path).
 */
IaxSerial *iax_serial_open(const IaxSerialConfig *cfg);

/**
 * Close the handle: stop the worker (its fail-safe drops the radio line on
 * the way out), then free. Never blocks indefinitely — a worker wedged in a
 * dead hardware transfer is detached after a short grace period (its device
 * is gone, so no radio line is left to unkey). NULL is a no-op.
 */
void iax_serial_close(IaxSerial *s);

/**
 * One keying tick: NON-BLOCKING (iax-239a). Publishes `remote_keyed`/`rx_db`
 * (from the consumer's `AstarStation` snapshot) to the worker thread — which
 * does the actual line I/O on its own ~20 ms cadence — and pops the next
 * pending debounced key edge. On return, `*out_changed` is `true` when the
 * call PTT should change, and `*out_set_ptt` holds the new value (only
 * meaningful when changed). Returns `IAX_OK` or a negative `IAX_ERR_*`:
 * `IAX_ERR_SERIAL` when the worker died (persistent backend failure) or
 * stalled (wedged hardware transfer) — tear the handle down and re-open once
 * the device is back.
 *
 * Call from a single thread per handle; see [`IaxSerial`].
 */
int iax_serial_ptt_tick(IaxSerial *s,
                        bool remote_keyed,
                        float rx_db,
                        bool *out_set_ptt,
                        bool *out_changed);

/**
 * Autodetect a serial port (first WCH USB device) and write its path into
 * `out` (NUL-terminated, `cap` bytes). Returns `IAX_OK`, `IAX_ERR_NO_DEVICE`,
 * `IAX_ERR_BUFFER` (path + NUL would not fit), or `IAX_ERR_NULL`.
 */
int iax_serial_autodetect(char *out, uintptr_t cap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ASTARSERIAL_H */
