#!/usr/bin/env bash
# astar — Copyright (c) 2026 Rob Ludwick.
# SPDX-License-Identifier: AGPL-3.0-only
# Licensed under the GNU Affero General Public License v3.0 only. See LICENSE.
# Orchestrate the Asterisk-in-Podman parity harness.
#
# Subcommands:
#   up                     bring Asterisk up (iax-6813 baseline)
#   down                   tear down the whole stack
#   refresh   [scenario]   refresh Rust-side fixtures (iax-6813)
#   up-c                   bring up Asterisk + the patched-C client container
#   refresh-c [scenario]   refresh C-side fixtures (iax-7022)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

cleanup() {
    podman stop $(podman ps --filter "name=tshark-" -q) 2>/dev/null || true
    podman stop $(podman ps --filter "name=tshark-c-" -q) 2>/dev/null || true
    podman compose down 2>/dev/null || true
}

wait_for_asterisk() {
    local deadline=$((SECONDS + 10))
    while (( SECONDS < deadline )); do
        if podman compose exec -T asterisk asterisk -rx 'iax2 show peers' >/dev/null 2>&1; then
            return 0
        fi
        sleep 0.2
    done
    echo "asterisk did not become ready within 10s" >&2
    podman compose logs asterisk >&2
    return 1
}

cmd_up() {
    podman compose up -d asterisk
    wait_for_asterisk
    echo "asterisk listening on 127.0.0.1:4569/udp"
}

cmd_down() {
    podman compose down
}

SCENARIOS=(register call_notoken call_token call_ulaw peer_hangup)
# C-side scenarios. The base SCENARIOS array drives the Rust harness;
# C-side adds register_reject (libiax2 register flow with no Rust analog)
# and incoming (asterisk-originated call to the C client, exercising the
# NEW-received path).
SCENARIOS_C=(register register_reject call_notoken call_token call_ulaw peer_hangup incoming)

user_for() {
    case "$1" in
        # No-token peer covers REGISTER and the no-CALLTOKEN call path.
        # The harness's register scenario sends hand-built REGREQs that
        # do not carry a CALLTOKEN IE, so the peer config must accept
        # plain auth.
        register|call_notoken) echo "astartest_notok" ;;
        *)                    echo "astartest" ;;
    esac
}

fixture_dir() {
    echo "../../crates/astar-conformance/fixtures/asterisk"
}

wait_for_tshark() {
    local container="$1"
    local deadline=$((SECONDS + 5))
    while (( SECONDS < deadline )); do
        if podman logs "$container" 2>&1 | grep -q "Capturing on"; then
            return 0
        fi
        sleep 0.1
    done
    echo "tshark sidecar $container did not enter capture loop within 5s" >&2
    return 1
}

write_companion() {
    local scenario="$1"
    cat > "$(fixture_dir)/${scenario}.md" <<EOF
# ${scenario}.pcap

Generated by harness/asterisk_parity (iax-6813) against a local
\`andrius/asterisk:20\` container with the configuration under
harness/asterisk_parity/asterisk/. Peer credentials:
$(user_for "$scenario"):supersecret.
EOF
}

refresh_one() {
    local scenario="$1"
    local user="$(user_for "$scenario")"
    local container="tshark-${scenario}"

    rm -f captures/active.pcap
    echo "starting tshark sidecar as $container..." >&2
    podman compose --profile capture run -d --rm --name "$container" tshark >/dev/null
    wait_for_tshark "$container"
    # Give chan_iax2 a beat past CLI-ready to fully bind the listener
    # before we drive packets at it. Without this, the first scenario
    # after a fresh `up` races with the IAX2 module initialization.
    sleep 1

    set +e
    PATH="/Users/rob/.rustup/toolchains/stable-aarch64-apple-darwin/bin:$PATH" \
        IAX_PEER=127.0.0.1:4569 \
        IAX_USER="$user" \
        IAX_SECRET=supersecret \
        cargo run --manifest-path=../../Cargo.toml \
                  -p astar-conformance --example harness --quiet -- "$scenario"
    local rc=$?
    set -e

    podman stop "$container" >/dev/null
    sleep 0.5   # tshark flush

    if (( rc != 0 )); then
        echo "scenario $scenario failed (exit $rc); refusing to overwrite fixture" >&2
        return $rc
    fi
    if [[ ! -s captures/active.pcap ]]; then
        echo "scenario $scenario produced empty pcap; refusing to overwrite fixture" >&2
        return 1
    fi

    mkdir -p "$(fixture_dir)"
    mv captures/active.pcap "$(fixture_dir)/${scenario}.pcap"
    write_companion "$scenario"
    echo "fixture refreshed: ${scenario}.pcap"
}

cmd_refresh() {
    cmd_up
    if (( $# >= 1 )); then
        refresh_one "$1"
    else
        for s in "${SCENARIOS[@]}"; do
            refresh_one "$s"
        done
    fi
}

# ---- C-side (iax-7022) ----

fixture_dir_c() {
    echo "../../crates/astar-conformance/fixtures/c-iaxclient"
}

wait_for_c_iaxclient() {
    local deadline=$((SECONDS + 30))   # build can take a moment
    while (( SECONDS < deadline )); do
        if podman compose exec -T c_iaxclient sh -c 'command -v iax-harness >/dev/null'; then
            return 0
        fi
        sleep 0.5
    done
    echo "c_iaxclient did not become ready within 30s" >&2
    podman compose logs c_iaxclient >&2
    return 1
}

cmd_up_c() {
    # Brings the C-client container up alongside asterisk. The build runs
    # the first time (vendored libiax2 + patches + harness.c); subsequent
    # invocations reuse the cached image unless something under
    # c_iaxclient/ changed.
    podman compose --profile c_client up -d asterisk c_iaxclient
    wait_for_asterisk
    wait_for_c_iaxclient
    echo "asterisk + c_iaxclient ready"
}

user_for_c() {
    # libiax2's iax_register does NOT send the empty-CALLTOKEN opt-in IE
    # (verified 2026-06-05 against patched snapshot), so register against a
    # requirecalltoken=yes peer yields REGREJ. Route register and the
    # explicit no-token call scenario through astartest_notok; everything
    # else uses astartest (libiax2 handles CALLTOKEN for iax_call).
    case "$1" in
        register|call_notoken) echo "astartest_notok" ;;
        # register_reject targets the CALLTOKEN-required peer on purpose,
        # so the missing-CALLTOKEN-IE behavior trips REGREJ.
        register_reject)       echo "astartest" ;;
        # incoming registers as astartest_notok so the registration leg
        # itself succeeds (sidesteps the libiax2 register-CALLTOKEN gap).
        incoming)              echo "astartest_notok" ;;
        *)                     echo "astartest" ;;
    esac
}

write_companion_c() {
    local scenario="$1"
    cat > "$(fixture_dir_c)/${scenario}.md" <<EOF
# ${scenario}.pcap (c-iaxclient)

Generated by harness/asterisk_parity (iax-7022) using the patched-C
iaxclient (snapshot under c_iaxclient/vendored/ + patches/) running in
debian:bookworm-slim against the same Asterisk image as the Rust-side
fixtures. Peer credentials: $(user_for_c "$scenario"):supersecret.

These captures are the ground truth for FSM-parity testing (iax-64f0)
against the Rust client.
EOF
}

asterisk_ip() {
    # Podman-compose's inline DNS for compose service names is unreliable
    # in this stack; libiax2's gethostbyname intermittently fails to
    # resolve "asterisk". Resolve once from the asterisk container's
    # network settings and pass the IP directly.
    podman inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' astar-test-asterisk
}

start_tshark_c() {
    local container="$1"
    rm -f captures/c-active.pcap
    echo "starting C-side tshark sidecar as $container..." >&2
    # Plain `podman run` (NOT `compose run`) so compose's dependency
    # tracker doesn't bounce c_iaxclient / asterisk under us. Joins
    # c_iaxclient's netns directly via --network container:<name>.
    podman run -d --rm --name "$container" \
        --network "container:astar-test-c-iaxclient" \
        --cap-add NET_ADMIN --cap-add NET_RAW \
        -v "$(pwd)/captures:/captures" \
        nicolaka/netshoot \
        tshark -i any -f "udp port 4569" -w /captures/c-active.pcap \
        >/dev/null
    wait_for_tshark "$container"
    sleep 1
}

# Run the harness binary against the C client, capturing stderr for the log.
# For the `incoming` scenario, the harness blocks waiting for an inbound
# NEW — the orchestrator triggers it from asterisk after a 3s window for
# registration to complete.
run_c_scenario() {
    local scenario="$1"
    local user="$2"
    local ip="$3"

    if [[ "$scenario" == "incoming" ]]; then
        # Kick off the harness in the background so we can drive asterisk
        # while it idles waiting for CONNECT.
        podman compose exec -T \
            -e IAX_PEER="${ip}:4569" \
            -e IAX_USER="$user" \
            -e IAX_SECRET="supersecret" \
            c_iaxclient iax-harness incoming &
        local pid=$!

        # Give libiax2's registration time to round-trip.
        sleep 3

        # Originate from asterisk's CLI. The IAX2/<peer> channel
        # resolves to the address astartest_notok registered from, so
        # asterisk dials c_iaxclient. `application Wait,3` plays nothing
        # and hangs up after 3s — enough to see the full setup+teardown.
        echo "asterisk: channel originate IAX2/${user} application Wait,3" >&2
        podman compose exec -T asterisk \
            asterisk -rx "channel originate IAX2/${user} application Wait,3"

        # Wait for the harness to exit (8s pump_until inside).
        wait "$pid"
        return $?
    fi

    podman compose exec -T \
        -e IAX_PEER="${ip}:4569" \
        -e IAX_USER="$user" \
        -e IAX_SECRET="supersecret" \
        c_iaxclient iax-harness "$scenario"
}

refresh_one_c() {
    local scenario="$1"
    local user="$(user_for_c "$scenario")"
    local container="tshark-c-${scenario}"
    local ip="${ASTERISK_IP:-$(asterisk_ip)}"
    if [[ -z "$ip" ]]; then
        echo "asterisk_ip lookup failed; is the stack up?" >&2
        return 1
    fi

    start_tshark_c "$container"

    set +e
    run_c_scenario "$scenario" "$user" "$ip"
    local rc=$?
    set -e

    podman stop "$container" >/dev/null
    sleep 0.5   # tshark flush

    if (( rc != 0 )); then
        echo "scenario $scenario (c) failed (exit $rc); refusing to overwrite fixture" >&2
        return $rc
    fi
    if [[ ! -s captures/c-active.pcap ]]; then
        echo "scenario $scenario (c) produced empty pcap; refusing to overwrite fixture" >&2
        return 1
    fi

    mkdir -p "$(fixture_dir_c)"
    mv captures/c-active.pcap "$(fixture_dir_c)/${scenario}.pcap"
    write_companion_c "$scenario"
    echo "fixture refreshed: c-iaxclient/${scenario}.pcap"
}

cmd_refresh_c() {
    cmd_up_c
    # Resolve the asterisk IP ONCE up front and pin it via env. Each
    # `compose run` for the tshark_c sidecar can trigger compose to bounce
    # the c_iaxclient service (its network_mode target), and the dependent
    # asterisk container sometimes gets a new IP across those bounces.
    # Resolving per-scenario was racing the bounce; pin and reuse instead.
    export ASTERISK_IP="$(asterisk_ip)"
    if [[ -z "$ASTERISK_IP" ]]; then
        echo "asterisk_ip lookup failed after up-c" >&2
        return 1
    fi
    echo "pinned asterisk at $ASTERISK_IP"

    if (( $# >= 1 )); then
        refresh_one_c "$1"
    else
        for s in "${SCENARIOS_C[@]}"; do
            refresh_one_c "$s"
        done
    fi
}

main() {
    local cmd="${1:-}"
    case "$cmd" in
        up)         shift; cmd_up "$@" ;;
        down)       shift; cmd_down "$@" ;;
        refresh)    shift; cmd_refresh "$@" ;;
        up-c)       shift; cmd_up_c "$@" ;;
        refresh-c)  shift; cmd_refresh_c "$@" ;;
        ""|-h|--help)
            cat <<'USAGE'
Usage: ./run.sh <subcommand>

  up                  Bring Asterisk up and wait for readiness.
  down                Tear down the whole harness stack.
  refresh [name]      Rebuild Rust-side fixture(s). Omit name to refresh all.

  up-c                Bring up Asterisk + the patched-C iaxclient container.
  refresh-c [name]    Rebuild C-side fixture(s) under
                      crates/astar-conformance/fixtures/c-iaxclient/.
USAGE
            ;;
        *) echo "unknown subcommand: $cmd" >&2; exit 2 ;;
    esac
}

trap cleanup EXIT INT TERM
main "$@"
trap - EXIT INT TERM
