#!/usr/bin/env bash
# astar — Copyright (c) 2026 Rob Ludwick.
# SPDX-License-Identifier: AGPL-3.0-only
# Licensed under the GNU Affero General Public License v3.0 only. See LICENSE.
# Build the Zensical documentation site.
#
# Zensical is the static site generator from the Material for MkDocs team; the
# config is ./zensical.toml at the repo root (TOML — NOT mkdocs.yml). It sets
# docs_dir = docs/site (the published pages) and site_dir = docs/.site (the
# build output, gitignored); this script reads site_dir back out of the config
# rather than hard-coding it, so a layout change there cannot silently make CI
# verify the wrong directory.
#
# `--strict` aborts on warnings, so a broken link or a nav entry pointing at a
# missing page reddens the pipeline instead of shipping a half-built site.
#
# It also generates the published release manifest, api/v1/releases.json — the
# file a running astar fetches to learn that a newer version exists. See
# docs/design/version-manifest.md and ci/version_manifest.py.
#
# This is the single build entry point shared by the GitLab `docs-site` job
# (which builds on every push) and the dormant GitHub Pages workflow (which
# uploads this output as the Pages artifact) — the verified site and the
# published site are therefore built by identical code.
#
# Toolchain: uses `uvx zensical` when uv is installed (fast, no venv to manage,
# matches the local recipes), otherwise falls back to a throwaway virtualenv
# and `pip install zensical`. Either way it needs network access once.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CONFIG="$ROOT/zensical.toml"
if [ ! -f "$CONFIG" ]; then
  echo "FAIL: no zensical.toml at the repo root ($CONFIG)." >&2
  echo "      If the docs site moved, point ci/build-docs.sh at its new home." >&2
  exit 1
fi

# site_dir straight from the config; fall back to Zensical's own default.
SITE_DIR="$(python3 - "$CONFIG" <<'PY'
import sys
try:
    import tomllib
    with open(sys.argv[1], "rb") as fh:
        print(tomllib.load(fh).get("project", {}).get("site_dir", "site"))
except Exception:
    print("site")
PY
)"
OUT="$ROOT/$SITE_DIR"

# The release manifest (docs/site/api/v1/releases.json), generated BEFORE the
# build so Zensical copies it into the site like any other static asset. It is
# gitignored: a generated file that has to be regenerated by hand on every
# changelog edit is the manual lockstep this whole exercise removes.
#
# --check first, as its own step, so a version spelled three different ways
# fails with that message rather than with a confusing manifest downstream.
# `just ci` runs the same check, so this is normally a formality here.
python3 "$ROOT/ci/version_manifest.py" --check
python3 "$ROOT/ci/version_manifest.py" --write "$ROOT/docs/site"

if command -v uvx >/dev/null 2>&1; then
  uvx zensical build --clean --strict
else
  # Built outside the working tree on purpose: nothing to add to .gitignore,
  # and `git clean` between jobs can never half-delete it.
  VENV="${DOCS_VENV:-${TMPDIR:-/tmp}/astar-docs-venv}"
  rm -rf "$VENV"
  python3 -m venv "$VENV"
  # shellcheck disable=SC1091
  . "$VENV/bin/activate"
  python3 -m pip install --quiet --upgrade pip
  python3 -m pip install --quiet zensical
  zensical build --clean --strict
fi

if [ ! -f "$OUT/index.html" ]; then
  echo "FAIL: zensical produced no $SITE_DIR/index.html" >&2
  exit 1
fi

if [ ! -f "$OUT/api/v1/releases.json" ]; then
  echo "FAIL: zensical did not copy api/v1/releases.json into $SITE_DIR." >&2
  echo "      Non-Markdown assets under docs_dir are supposed to pass through" >&2
  echo "      verbatim; if that changed, write the manifest into $SITE_DIR" >&2
  echo "      after the build instead." >&2
  exit 1
fi

# Every notes_url the manifest emitted points at a heading anchor on the built
# changelog page. The slug rule is Python-Markdown's, and this proves it still
# is rather than trusting a comment about it.
python3 "$ROOT/ci/version_manifest.py" --verify-anchors "$OUT"

echo "docs: built $(find "$OUT" -type f | wc -l | tr -d ' ') files into $SITE_DIR"
