[astar-router]
exten => s,1,Goto(astar-echo,s,1)
exten => bye,1,Goto(astar-bye,s,1)

[astar-echo]
exten => s,1,Answer()
 same => n,Wait(1)
 same => n,Playback(demo-echotest)
 same => n,Echo()
 same => n,Hangup()

[astar-bye]
exten => s,1,Answer()
 same => n,Wait(0)
 same => n,Hangup()
